// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

public typealias WindowsSystemRemoteDesktopInput_RemoteTextConnectionDataHandler = ([Swift.UInt8]) throws -> Swift.Bool