// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// An enum that describes the reason for move the focus.
public struct WindowsWebUIInterop_WebViewControlMoveFocusReason: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Focus was moved programmatically.
    public static let programmatic = Self()

    /// Focus was moved to the next.
    public static let next = Self(rawValue: 1)

    /// Focus was moved to the previous.
    public static let previous = Self(rawValue: 2)
}