// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides information for the AppExtensionCatalog.PackageUpdating event.
public final class WindowsApplicationModelAppExtensions_AppExtensionPackageUpdatingEventArgs: WindowsRuntime.WinRTImport<WindowsApplicationModelAppExtensions_AppExtensionPackageUpdatingEventArgsProjection> {
    // MARK: Windows.ApplicationModel.AppExtensions.IAppExtensionPackageUpdatingEventArgs members

    /// Gets the name of the app extension that is being updated.
    /// - Returns: The name of the app extension.
    public var appExtensionName: Swift.String {
        get throws {
            try _interop.get_AppExtensionName()
        }
    }

    /// Provides the package containing the extension that is updating.
    /// - Returns: The updated app extension package.
    public var package: WindowsApplicationModel_Package {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Package())
        }
    }

    // MARK: Implementation details
}