// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides information for the AppExtensionCatalog.PackageUpdated event.
public final class WindowsApplicationModelAppExtensions_AppExtensionPackageUpdatedEventArgs: WindowsRuntime.WinRTImport<WindowsApplicationModelAppExtensions_AppExtensionPackageUpdatedEventArgsProjection> {
    // MARK: Windows.ApplicationModel.AppExtensions.IAppExtensionPackageUpdatedEventArgs members

    /// Gets the name of the app extension that was updated.
    /// - Returns: The name of the updated app extension.
    public var appExtensionName: Swift.String {
        get throws {
            try _interop.get_AppExtensionName()
        }
    }

    /// Provides a list of extensions that are in the extension package that was updated
    /// - Returns: A list of extensions within the updated extension package.
    public var extensions: WindowsFoundationCollections_IVectorView<WindowsApplicationModelAppExtensions_AppExtension?> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Extensions())
        }
    }

    /// Provides the package containing the extension that was updated.
    /// - Returns: The updated app extension package.
    public var package: WindowsApplicationModel_Package {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Package())
        }
    }

    // MARK: Implementation details
}