// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies each possible response for a ConversationalAgentSession update.
public struct WindowsApplicationModelConversationalAgent_ConversationalAgentSessionUpdateResponse: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Indicates a ConversationalAgentSession update succeeded.
    public static let success = Self()

    /// Indicates a ConversationalAgentSession update failed.
    public static let failed = Self(rawValue: 1)
}