// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// The progress data for an asynchronous photo import operation.
public struct WindowsMediaImport_PhotoImportProgress: Hashable, Codable {
    /// The number of items that have been imported.
    public var itemsImported: Swift.UInt32

    /// The total number of items to be imported.
    public var totalItemsToImport: Swift.UInt32

    /// The number of bytes that have been imported.
    public var bytesImported: Swift.UInt64

    /// The total number of bytes to be imported.
    public var totalBytesToImport: Swift.UInt64

    /// The current import progress, expressed as a floating point value from 0 to 1.
    public var importProgress: Swift.Double

    public init() {
        self.itemsImported = 0
        self.totalItemsToImport = 0
        self.bytesImported = 0
        self.totalBytesToImport = 0
        self.importProgress = 0
    }

    public init(itemsImported: Swift.UInt32, totalItemsToImport: Swift.UInt32, bytesImported: Swift.UInt64, totalBytesToImport: Swift.UInt64, importProgress: Swift.Double) {
        self.itemsImported = itemsImported
        self.totalItemsToImport = totalItemsToImport
        self.bytesImported = bytesImported
        self.totalBytesToImport = totalBytesToImport
        self.importProgress = importProgress
    }
}