// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Contains properties that are passed to an application with the ConnectionRequested event.
public final class WindowsNetworkingProximity_ConnectionRequestedEventArgs: WindowsRuntime.WinRTImport<WindowsNetworkingProximity_ConnectionRequestedEventArgsProjection> {
    // MARK: Windows.Networking.Proximity.IConnectionRequestedEventArgs members

    /// Gets the information for a peer that's requesting a connection.
    /// - Returns: The information for a peer that's requesting a connection.
    public var peerInformation: WindowsNetworkingProximity_PeerInformation {
        get throws {
            try COM.NullResult.unwrap(_interop.get_PeerInformation())
        }
    }

    // MARK: Implementation details
}