// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Identifies a property of AutomationElementIdentifiers or of a specific control pattern.
public final class WindowsUIXamlAutomation_AutomationProperty: WindowsRuntime.WinRTImport<WindowsUIXamlAutomation_AutomationPropertyProjection> {
    // MARK: Implementation details
}