// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

public final class WindowsUIViewManagementCore_CoreInputViewAnimationStartingEventArgs: WindowsRuntime.WinRTImport<WindowsUIViewManagementCore_CoreInputViewAnimationStartingEventArgsProjection> {
    // MARK: Windows.UI.ViewManagement.Core.ICoreInputViewAnimationStartingEventArgs members

    public var animationDuration: WindowsFoundation_TimeSpan {
        get throws {
            try _interop.get_AnimationDuration()
        }
    }

    public var handled: Swift.Bool {
        get throws {
            try _interop.get_Handled()
        }
    }

    public func handled(_ value: Swift.Bool) throws {
        try _interop.put_Handled(value)
    }

    public var occlusions: WindowsFoundationCollections_IVectorView<WindowsUIViewManagementCore_CoreInputViewOcclusion?> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Occlusions())
        }
    }

    // MARK: Implementation details
}