// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// This class exposes a single static method used to check if a list of App Capabilities is supported on the current device.
public enum WindowsSystemProfile_AppApplicability {
    // MARK: Windows.System.Profile.IAppApplicabilityStatics members

    public static func getUnsupportedAppRequirements(_ capabilities: WindowsFoundationCollections_IIterable<Swift.String>?) throws -> WindowsFoundationCollections_IVectorView<WindowsSystemProfile_UnsupportedAppRequirement?> {
        try COM.NullResult.unwrap(_iappApplicabilityStatics.getUnsupportedAppRequirements(capabilities))
    }

    // MARK: Implementation details

    private static var _iappApplicabilityStatics_storage: COM.COMInterop<CWinRT.SWRT_WindowsSystemProfile_IAppApplicabilityStatics>? = nil

    internal static var _iappApplicabilityStatics: COM.COMInterop<CWinRT.SWRT_WindowsSystemProfile_IAppApplicabilityStatics> {
        get throws {
            try _iappApplicabilityStatics_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.System.Profile.AppApplicability", id: CWinRT.SWRT_WindowsSystemProfile_IAppApplicabilityStatics.iid)
            }
        }
    }
}