// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Contains continuous recognition event data for the SpeechContinuousRecognitionSession.Completed event.
public final class WindowsMediaSpeechRecognition_SpeechContinuousRecognitionCompletedEventArgs: WindowsRuntime.WinRTImport<WindowsMediaSpeechRecognition_SpeechContinuousRecognitionCompletedEventArgsProjection> {
    // MARK: Windows.Media.SpeechRecognition.ISpeechContinuousRecognitionCompletedEventArgs members

    /// Gets the status of a continuous speech recognition session (or the result of a grammar constraint compilation).
    /// - Returns: The status of a continuous speech recognition session (or the result of a grammar constraint compilation).
    public var status: WindowsMediaSpeechRecognition_SpeechRecognitionResultStatus {
        get throws {
            try _interop.get_Status()
        }
    }

    // MARK: Implementation details
}