// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Describes the types of standard color spaces for display monitors.
public struct WindowsGraphicsDisplayCore_HdmiDisplayColorSpace: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Limited RGB; levels are limited to 16-235.
    public static let rgbLimited = Self()

    /// Full RGB; levels are in the full range of 0-255.
    public static let rgbFull = Self(rawValue: 1)

    /// The ITU-R Recommendation BT.2020 is the recommended format for ultra-high-definition TV (UHDTV).
    public static let bt2020 = Self(rawValue: 2)

    /// The ITU-R Recommendation BT.709 is the recommended format for high-definition TV (HDTV).
    public static let bt709 = Self(rawValue: 3)
}