// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// **VpnNamespaceAssignment** is not supported and may be altered or unavailable in the future. Instead, use VpnDomainNameAssignment.
public final class WindowsNetworkingVpn_VpnNamespaceAssignment: WindowsRuntime.WinRTImport<WindowsNetworkingVpn_VpnNamespaceAssignmentProjection> {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsNetworkingVpn_VpnNamespaceAssignmentProjection.self))
    }

    // MARK: Windows.Networking.Vpn.IVpnNamespaceAssignment members

    /// Not supported.
    /// - Returns: Not supported.
    public var namespaceList: WindowsFoundationCollections_IVector<WindowsNetworkingVpn_VpnNamespaceInfo?> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_NamespaceList())
        }
    }

    /// Not supported.
    /// - Returns: Not supported.
    public func namespaceList(_ value: WindowsFoundationCollections_IVector<WindowsNetworkingVpn_VpnNamespaceInfo?>?) throws {
        try _interop.put_NamespaceList(value)
    }

    /// Not supported.
    /// - Returns: Not supported.
    public var proxyAutoConfigUri: WindowsFoundation_Uri {
        get throws {
            try COM.NullResult.unwrap(_interop.get_ProxyAutoConfigUri())
        }
    }

    /// Not supported.
    /// - Returns: Not supported.
    public func proxyAutoConfigUri(_ value: WindowsFoundation_Uri?) throws {
        try _interop.put_ProxyAutoConfigUri(value)
    }

    // MARK: Implementation details

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.Networking.Vpn.VpnNamespaceAssignment", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }
}