// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides data for the NavigationStarting and FrameNavigationStarting events.
public final class WindowsWebUI_WebViewControlNavigationStartingEventArgs: WindowsRuntime.WinRTImport<WindowsWebUI_WebViewControlNavigationStartingEventArgsProjection> {
    // MARK: Windows.Web.UI.IWebViewControlNavigationStartingEventArgs members

    /// Gets or sets a value indicating whether to cancel the IWebViewControl navigation.
    /// - Returns: **true** to cancel the navigation; otherwise, **false**.
    public var cancel: Swift.Bool {
        get throws {
            try _interop.get_Cancel()
        }
    }

    /// Gets or sets a value indicating whether to cancel the IWebViewControl navigation.
    /// - Returns: **true** to cancel the navigation; otherwise, **false**.
    public func cancel(_ value: Swift.Bool) throws {
        try _interop.put_Cancel(value)
    }

    /// Gets the Uniform Resource Identifier (URI) of the content the IWebViewControl is loading.
    /// - Returns: The Uniform Resource Identifier (URI) of the content.
    public var uri: WindowsFoundation_Uri {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Uri())
        }
    }

    // MARK: Implementation details
}