// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a connection within an audio graph.
public final class WindowsMediaAudio_AudioGraphConnection: WindowsRuntime.WinRTImport<WindowsMediaAudio_AudioGraphConnectionProjection> {
    // MARK: Windows.Media.Audio.IAudioGraphConnection members

    /// Gets the destination node for the connection.
    /// - Returns: The **IAudioNode** interface for the destination node.
    public var destination: WindowsMediaAudio_IAudioNode {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Destination())
        }
    }

    /// Gets the gain associated with the audio graph connection.
    /// - Returns: A value indicating the gain.
    public var gain: Swift.Double {
        get throws {
            try _interop.get_Gain()
        }
    }

    /// Gets the gain associated with the audio graph connection.
    /// - Returns: A value indicating the gain.
    public func gain(_ value: Swift.Double) throws {
        try _interop.put_Gain(value)
    }

    // MARK: Implementation details
}