// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Possible values for the persistence of a global qualifier value override.
public struct WindowsApplicationModelResourcesCore_ResourceQualifierPersistence: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The override value is not persistent.
    public static let none = Self()

    /// The override value persists on the local machine.
    public static let localMachine = Self(rawValue: 1)
}