// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides the property values for a PlayReady-ND transmitter certificate.
public protocol WindowsMediaProtectionPlayReady_INDTransmitterPropertiesProtocol: IInspectableProtocol {
    /// Gets the certificate type for the transmitter.
    /// - Returns: The certificate type. This value can be either **DRM_BCERT_CERTTYPE_PC** (0x1) or **DRM_BCERT_CERTTYPE_DEVICE** (0x2).
    var certificateType: WindowsMediaProtectionPlayReady_NDCertificateType { get throws }

    /// Gets the client identifier from the transmitter certificate.
    /// - Returns: The client identifier.
    var clientID: [Swift.UInt8] { get throws }

    /// Gets the expiration date and time from the transmitter certificate.
    /// - Returns: The date and time the certificate expires.
    var expirationDate: WindowsFoundation_DateTime { get throws }

    /// Gets the model digest from a transmitter certificate.
    /// - Returns: The model digest.
    var modelDigest: [Swift.UInt8] { get throws }

    /// Gets the model manufacturer name from a transmitter certificate.
    /// - Returns: The model manufacturer name.
    var modelManufacturerName: Swift.String { get throws }

    /// Gets the model name from a transmitter certificate.
    /// - Returns: The model name.
    var modelName: Swift.String { get throws }

    /// Gets the model number from a transmitter certificate.
    /// - Returns: The model number as a text string.
    var modelNumber: Swift.String { get throws }

    /// Gets the platform identifier from a transmitter certificate.
    /// - Returns: The platform identifier.
    var platformIdentifier: WindowsMediaProtectionPlayReady_NDCertificatePlatformID { get throws }

    /// Gets the security level from a transmitter certificate.
    /// - Returns: The security level.
    var securityLevel: Swift.UInt32 { get throws }

    /// Gets the security version from a transmitter certificate.
    /// - Returns: The security version.
    var securityVersion: Swift.UInt32 { get throws }

    /// Gets the list of supported features from the transmitter certificate.
    /// - Returns: An array identifying the feature sets that the certificate supports.
    var supportedFeatures: [WindowsMediaProtectionPlayReady_NDCertificateFeature] { get throws }
}

/// Provides the property values for a PlayReady-ND transmitter certificate.
public typealias WindowsMediaProtectionPlayReady_INDTransmitterProperties = any WindowsMediaProtectionPlayReady_INDTransmitterPropertiesProtocol