// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Indicates the type of format used for closed captions.
public struct WindowsMediaProtectionPlayReady_NDClosedCaptionFormat: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// ATSC digital television closed captions.
    public static let atsc = Self()

    /// SCTE 20 MPEG2 closed captions.
    public static let scte20 = Self(rawValue: 1)

    /// Invalid format.
    public static let unknown = Self(rawValue: 2)
}