// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Contains methods that a download engine plug-in uses to send notifications to a PlayReady-ND client.
public final class WindowsMediaProtectionPlayReady_NDDownloadEngineNotifier: WindowsRuntime.WinRTImport<WindowsMediaProtectionPlayReady_NDDownloadEngineNotifierProjection>, WindowsMediaProtectionPlayReady_INDDownloadEngineNotifierProtocol {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsMediaProtectionPlayReady_NDDownloadEngineNotifierProjection.self))
    }

    // MARK: Windows.Media.Protection.PlayReady.INDDownloadEngineNotifier members

    /// Called by the download engine when a stream is opened.
    public func onStreamOpened() throws {
        try _interop.onStreamOpened()
    }

    /// Called by the download engine once a PlayReady object is received.
    /// - Parameter dataBytes: The byte array that holds the PlayReady object.
    public func onPlayReadyObjectReceived(_ dataBytes: [Swift.UInt8]) throws {
        try _interop.onPlayReadyObjectReceived(dataBytes)
    }

    /// Called by the download engine when a content identifier is received.
    /// - Parameter licenseFetchDescriptor: The license from which the download engine receives the content identifier.
    public func onContentIDReceived(_ licenseFetchDescriptor: WindowsMediaProtectionPlayReady_INDLicenseFetchDescriptor?) throws {
        try _interop.onContentIDReceived(licenseFetchDescriptor)
    }

    /// Called by the download engine when it receives data.
    /// - Parameter dataBytes: The byte array that holds the data.
    /// - Parameter bytesReceived: The number of bytes received from the data stream.
    public func onDataReceived(_ dataBytes: [Swift.UInt8], _ bytesReceived: Swift.UInt32) throws {
        try _interop.onDataReceived(dataBytes, bytesReceived)
    }

    /// Called by the download engine when it reaches the end of a PlayReady-ND media stream.
    public func onEndOfStream() throws {
        try _interop.onEndOfStream()
    }

    /// Called by the download engine if an error occurs during downloading.
    public func onNetworkError() throws {
        try _interop.onNetworkError()
    }

    // MARK: Implementation details

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.Media.Protection.PlayReady.NDDownloadEngineNotifier", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }
}