// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides a block-level content element that is used to group content into a paragraph.
public final class WindowsUIXamlDocuments_Paragraph: WindowsRuntime.WinRTImport<WindowsUIXamlDocuments_ParagraphProjection> {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsUIXamlDocuments_ParagraphProjection.self))
    }

    // MARK: Windows.UI.Xaml.Documents.IParagraph members

    /// Gets an InlineCollection containing the top-level Inline elements that include the contents of the Paragraph.
    /// - Returns: An InlineCollection containing the Inline elements that include the contents of the Paragraph.
    public var inlines: WindowsUIXamlDocuments_InlineCollection {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Inlines())
        }
    }

    /// Gets or sets the indentation of the first line of text in a paragraph, in pixels.
    /// - Returns: The offset amount, in pixels, of the first line of text in a paragraph.
    public var textIndent: Swift.Double {
        get throws {
            try _interop.get_TextIndent()
        }
    }

    /// Gets or sets the indentation of the first line of text in a paragraph, in pixels.
    /// - Returns: The offset amount, in pixels, of the first line of text in a paragraph.
    public func textIndent(_ value: Swift.Double) throws {
        try _interop.put_TextIndent(value)
    }

    // MARK: Windows.UI.Xaml.Documents.IParagraphStatics members

    /// Identifies the TextIndent dependency property.
    /// - Returns: The identifier for the TextIndent dependency property.
    public static var textIndentProperty: WindowsUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_iparagraphStatics.get_TextIndentProperty())
        }
    }

    // MARK: Implementation details

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Documents.Paragraph", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }

    private static var _iparagraphStatics_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlDocuments_IParagraphStatics>? = nil

    internal static var _iparagraphStatics: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlDocuments_IParagraphStatics> {
        get throws {
            try _iparagraphStatics_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Documents.Paragraph", id: CWinRT.SWRT_WindowsUIXamlDocuments_IParagraphStatics.iid)
            }
        }
    }
}