// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a discrete section of formatted or unformatted text.
public final class WindowsUIXamlDocuments_Run: WindowsRuntime.WinRTImport<WindowsUIXamlDocuments_RunProjection> {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsUIXamlDocuments_RunProjection.self))
    }

    // MARK: Windows.UI.Xaml.Documents.IRun members

    /// Gets or sets the direction that text and other user interface elements flow within the Run element that controls their layout.
    /// - Returns: The direction that text and other user interface (UI) elements flow within the Run element. The default value is **LeftToRight**.
    public var flowDirection: WindowsUIXaml_FlowDirection {
        get throws {
            try _interop.get_FlowDirection()
        }
    }

    /// Gets or sets the direction that text and other user interface elements flow within the Run element that controls their layout.
    /// - Returns: The direction that text and other user interface (UI) elements flow within the Run element. The default value is **LeftToRight**.
    public func flowDirection(_ value: WindowsUIXaml_FlowDirection) throws {
        try _interop.put_FlowDirection(value)
    }

    /// Gets or sets the text contents of the Run.
    /// - Returns: A string that specifies the text contents of the Run. The default is String.Empty.
    public var text: Swift.String {
        get throws {
            try _interop.get_Text()
        }
    }

    /// Gets or sets the text contents of the Run.
    /// - Returns: A string that specifies the text contents of the Run. The default is String.Empty.
    public func text(_ value: Swift.String) throws {
        try _interop.put_Text(value)
    }

    // MARK: Windows.UI.Xaml.Documents.IRunStatics members

    /// Identifies the FlowDirection  dependency property.
    /// - Returns: The identifier of the FlowDirection  dependency property.
    public static var flowDirectionProperty: WindowsUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_irunStatics.get_FlowDirectionProperty())
        }
    }

    // MARK: Implementation details

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Documents.Run", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }

    private static var _irunStatics_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlDocuments_IRunStatics>? = nil

    internal static var _irunStatics: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlDocuments_IRunStatics> {
        get throws {
            try _irunStatics_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Documents.Run", id: CWinRT.SWRT_WindowsUIXamlDocuments_IRunStatics.iid)
            }
        }
    }
}