// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the root element for a subtree that is created for a group.
open class WindowsUIXamlControls_GroupItem: WindowsRuntime.WinRTComposableClass {
    // MARK: Windows.UI.Xaml.Controls.IGroupItemFactory members

    public convenience init() throws {
        try self.init(_compose: Self.self != WindowsUIXamlControls_GroupItem.self) {
            (baseInterface, innerInterface: inout IInspectablePointer?) in
            try COM.NullResult.unwrap(Self._igroupItemFactory.createInstance(baseInterface, &innerInterface))
        }
    }

    // MARK: Implementation details

    private var _igroupItem_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlControls_IGroupItem>? = nil

    internal var _igroupItem: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlControls_IGroupItem> {
        get throws {
            try _igroupItem_storage.lazyInit {
                try _queryInnerInterfacePointer(CWinRT.SWRT_WindowsUIXamlControls_IGroupItem.iid).cast(to: CWinRT.SWRT_WindowsUIXamlControls_IGroupItem.self)
            }
        }
    }

    public init(_transferringRef comPointer: Swift.UnsafeMutablePointer<CWinRT.SWRT_WindowsUIXamlControls_IGroupItem>) {
        super.init(_transferringRef: IInspectablePointer.cast(comPointer))
    }

    public override init<Interface>(_compose: Swift.Bool, _factory: ComposableFactory<Interface>) throws {
        try super.init(_compose: _compose, _factory: _factory)
    }

    deinit {
        _igroupItem_storage?.release()
    }

    private static var _igroupItemFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlControls_IGroupItemFactory>? = nil

    internal static var _igroupItemFactory: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlControls_IGroupItemFactory> {
        get throws {
            try _igroupItemFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Controls.GroupItem", id: CWinRT.SWRT_WindowsUIXamlControls_IGroupItemFactory.iid)
            }
        }
    }
}