// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides event data for the HandwritingView.Opened event.
public final class WindowsUIXamlControls_HandwritingPanelOpenedEventArgs: WindowsRuntime.WinRTImport<WindowsUIXamlControls_HandwritingPanelOpenedEventArgsProjection> {
    // MARK: Implementation details
}