// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents an InkToolbar toggle button control that activates the built-in pencil.
open class WindowsUIXamlControls_InkToolbarPencilButton: WindowsRuntime.WinRTComposableClass {
    // MARK: Windows.UI.Xaml.Controls.IInkToolbarPencilButtonFactory members

    public convenience init() throws {
        try self.init(_compose: Self.self != WindowsUIXamlControls_InkToolbarPencilButton.self) {
            (baseInterface, innerInterface: inout IInspectablePointer?) in
            try COM.NullResult.unwrap(Self._iinkToolbarPencilButtonFactory.createInstance(baseInterface, &innerInterface))
        }
    }

    // MARK: Implementation details

    private var _iinkToolbarPencilButton_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlControls_IInkToolbarPencilButton>? = nil

    internal var _iinkToolbarPencilButton: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlControls_IInkToolbarPencilButton> {
        get throws {
            try _iinkToolbarPencilButton_storage.lazyInit {
                try _queryInnerInterfacePointer(CWinRT.SWRT_WindowsUIXamlControls_IInkToolbarPencilButton.iid).cast(to: CWinRT.SWRT_WindowsUIXamlControls_IInkToolbarPencilButton.self)
            }
        }
    }

    public init(_transferringRef comPointer: Swift.UnsafeMutablePointer<CWinRT.SWRT_WindowsUIXamlControls_IInkToolbarPencilButton>) {
        super.init(_transferringRef: IInspectablePointer.cast(comPointer))
    }

    public override init<Interface>(_compose: Swift.Bool, _factory: ComposableFactory<Interface>) throws {
        try super.init(_compose: _compose, _factory: _factory)
    }

    deinit {
        _iinkToolbarPencilButton_storage?.release()
    }

    private static var _iinkToolbarPencilButtonFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlControls_IInkToolbarPencilButtonFactory>? = nil

    internal static var _iinkToolbarPencilButtonFactory: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlControls_IInkToolbarPencilButtonFactory> {
        get throws {
            try _iinkToolbarPencilButtonFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Controls.InkToolbarPencilButton", id: CWinRT.SWRT_WindowsUIXamlControls_IInkToolbarPencilButtonFactory.iid)
            }
        }
    }
}