// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides event data for the SearchBox.QueryChanged event.
public final class WindowsUIXamlControls_SearchBoxQueryChangedEventArgs: WindowsRuntime.WinRTImport<WindowsUIXamlControls_SearchBoxQueryChangedEventArgsProjection> {
    // MARK: Windows.UI.Xaml.Controls.ISearchBoxQueryChangedEventArgs members

    /// Gets the Internet Engineering Task Force (IETF) language tag (BCP 47 standard) that identifies the language currently associated with the user's text input device.
    /// - Returns: The IETF BCP 47 standard language tag.
    public var language: Swift.String {
        get throws {
            try _interop.get_Language()
        }
    }

    /// Gets information about query text that the user enters through an Input Method Editor (IME).
    /// - Returns: Linguistic information about query text that the user enters through an Input Method Editor (IME).
    public var linguisticDetails: WindowsApplicationModelSearch_SearchQueryLinguisticDetails {
        get throws {
            try COM.NullResult.unwrap(_interop.get_LinguisticDetails())
        }
    }

    /// Gets the query text of the current search.
    /// - Returns: The query text of the current search.
    public var queryText: Swift.String {
        get throws {
            try _interop.get_QueryText()
        }
    }

    // MARK: Implementation details
}