// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// A bounding frustum in the user's surroundings defined as a set of 6 planes, with coordinates expressed in meters.
public struct WindowsPerceptionSpatial_SpatialBoundingFrustum: Hashable, Codable {
    /// The near Plane defines the boundary for the closest content within the frustum.
    public var near: WindowsFoundationNumerics_Plane

    /// The far Plane defines the boundary for the farthest content within the frustum.
    public var far: WindowsFoundationNumerics_Plane

    /// The right Plane defines the boundary for the rightmost content within the frustum.
    public var right: WindowsFoundationNumerics_Plane

    /// The left Plane defines the boundary for the leftmost content within the frustum.
    public var left: WindowsFoundationNumerics_Plane

    /// The top Plane defines the boundary for the topmost content within the frustum.
    public var top: WindowsFoundationNumerics_Plane

    /// The bottom Plane defines the boundary for the bottommost content within the frustum.
    public var bottom: WindowsFoundationNumerics_Plane

    public init() {
        self.near = .init()
        self.far = .init()
        self.right = .init()
        self.left = .init()
        self.top = .init()
        self.bottom = .init()
    }

    public init(near: WindowsFoundationNumerics_Plane, far: WindowsFoundationNumerics_Plane, right: WindowsFoundationNumerics_Plane, left: WindowsFoundationNumerics_Plane, top: WindowsFoundationNumerics_Plane, bottom: WindowsFoundationNumerics_Plane) {
        self.near = near
        self.far = far
        self.right = right
        self.left = left
        self.top = top
        self.bottom = bottom
    }
}