// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Contains the updated properties of a PnpObject.
public final class WindowsDevicesEnumerationPnp_PnpObjectUpdate: WindowsRuntime.WinRTImport<WindowsDevicesEnumerationPnp_PnpObjectUpdateProjection> {
    // MARK: Windows.Devices.Enumeration.Pnp.IPnpObjectUpdate members

    /// The identifier of the PnpObject.
    /// - Returns: The identifier of the PnpObject.
    public var id: Swift.String {
        get throws {
            try _interop.get_Id()
        }
    }

    /// The changed properties in an update to a PnpObject.
    /// - Returns: The changed properties.
    public var properties: WindowsFoundationCollections_IMapView<Swift.String, WindowsRuntime.IInspectable?> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Properties())
        }
    }

    /// The type of the PnpObject. One of the values of the PnpObjectType enumeration.
    /// - Returns: The type of the PnpObject.
    public var type: WindowsDevicesEnumerationPnp_PnpObjectType {
        get throws {
            try _interop.get_Type()
        }
    }

    // MARK: Implementation details
}