// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies the types of memory that can be used for a media operation.
public struct WindowsMediaEffects_MediaMemoryTypes: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// GPU memory.
    public static let gpu = Self()

    /// CPU memory.
    public static let cpu = Self(rawValue: 1)

    /// Both GPU and CPU memory.
    public static let gpuAndCpu = Self(rawValue: 2)
}