// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides data for the MediaPlaybackList.ItemOpened event.
public final class WindowsMediaPlayback_MediaPlaybackItemOpenedEventArgs: WindowsRuntime.WinRTImport<WindowsMediaPlayback_MediaPlaybackItemOpenedEventArgsProjection> {
    // MARK: Windows.Media.Playback.IMediaPlaybackItemOpenedEventArgs members

    /// Gets the MediaPlaybackItem that was successfully opened.
    /// - Returns: The MediaPlaybackItem that was successfully opened.
    public var item: WindowsMediaPlayback_MediaPlaybackItem {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Item())
        }
    }

    // MARK: Implementation details
}