// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a marker at specific location in a media stream time-line.
public final class WindowsMediaPlayback_PlaybackMediaMarker: WindowsRuntime.WinRTImport<WindowsMediaPlayback_PlaybackMediaMarkerProjection> {
    // MARK: Windows.Media.Playback.IPlaybackMediaMarkerFactory members

    public convenience init(_ value: WindowsFoundation_TimeSpan) throws {
        self.init(_transferringRef: try COM.NullResult.unwrap(Self._iplaybackMediaMarkerFactory.createFromTime(value)))
    }

    public convenience init(_ value: WindowsFoundation_TimeSpan, _ mediaMarketType: Swift.String, _ text: Swift.String) throws {
        self.init(_transferringRef: try COM.NullResult.unwrap(Self._iplaybackMediaMarkerFactory.create(value, mediaMarketType, text)))
    }

    // MARK: Windows.Media.Playback.IPlaybackMediaMarker members

    /// Gets the type of the media marker.
    /// - Returns: The type of the media marker.
    public var mediaMarkerType: Swift.String {
        get throws {
            try _interop.get_MediaMarkerType()
        }
    }

    /// Gets the text associated with the marker.
    /// - Returns: The text associated with the marker.
    public var text: Swift.String {
        get throws {
            try _interop.get_Text()
        }
    }

    /// Gets the offset in the media timeline where the marker occurs.
    /// - Returns: The offset in the media timeline where the marker occurs.
    public var time: WindowsFoundation_TimeSpan {
        get throws {
            try _interop.get_Time()
        }
    }

    // MARK: Implementation details

    private static var _iplaybackMediaMarkerFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsMediaPlayback_IPlaybackMediaMarkerFactory>? = nil

    internal static var _iplaybackMediaMarkerFactory: COM.COMInterop<CWinRT.SWRT_WindowsMediaPlayback_IPlaybackMediaMarkerFactory> {
        get throws {
            try _iplaybackMediaMarkerFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.Media.Playback.PlaybackMediaMarker", id: CWinRT.SWRT_WindowsMediaPlayback_IPlaybackMediaMarkerFactory.iid)
            }
        }
    }
}