// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies whether a set of timed metadata tracks are listed in the XAML **MediaTransportControls, whether events are raised for data cues in the tracks, and whether any subtitles and closed captions contained in the tracks are displayed by the system, by the app, or not at all.
public struct WindowsMediaPlayback_TimedMetadataTrackPresentationMode: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The timed metadata track is not listed in the **MediaTransportControls**. If the metadata track contains subtitles or closed captions, they are not displayed by the platform. Cue events are not raised.
    public static let disabled = Self()

    /// The timed metadata track is not listed in the **MediaTransportControls**. If the metadata track contains subtitles or closed captions, they are not displayed by the platform. Cue events are raised.
    public static let hidden = Self(rawValue: 1)

    /// The timed metadata track is listed in the **MediaTransportControls**. If the metadata track contains subtitles or closed captions, they are not displayed by the platform. Cue events are raised.
    public static let applicationPresented = Self(rawValue: 2)

    /// The timed metadata track is listed in the **MediaTransportControls**. If the metadata track contains subtitles or closed captions, they are displayed by the platform. Cue events are raised.
    public static let platformPresented = Self(rawValue: 3)
}