// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Defines constants that describe a level of supported IP. The values reflect the WWAN_IP_TYPE enumeration. You can use these values to determine which cellular profile to use (for example, to choose between IMS and SUPL).
public struct WindowsNetworkingConnectivity_WwanNetworkIPKind: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Default support; indicates no specific level of support.
    public static let none = Self()

    /// Indicates support for IPv4.
    public static let ipv4 = Self(rawValue: 1)

    /// Indicates support for IPv6.
    public static let ipv6 = Self(rawValue: 2)

    /// Indicates support for IPv4 with IPv6.
    public static let ipv4v6 = Self(rawValue: 3)

    /// Indicates support for 464XLAT (which allows clients on IPv6-only networks to access IPv4-only Internet services).
    public static let ipv4v6v4Xlat = Self(rawValue: 4)
}