// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a chapter cue that can be included in a TimedMetadataTrack.
public final class WindowsMediaCore_ChapterCue: WindowsRuntime.WinRTImport<WindowsMediaCore_ChapterCueProjection>, WindowsMediaCore_IMediaCueProtocol {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsMediaCore_ChapterCueProjection.self))
    }

    // MARK: Windows.Media.Core.IChapterCue members

    /// Gets the title of the chapter associated with the cue.
    /// - Returns: The title of the chapter
    public var title: Swift.String {
        get throws {
            try _interop.get_Title()
        }
    }

    /// Gets the title of the chapter associated with the cue.
    /// - Returns: The title of the chapter
    public func title(_ value: Swift.String) throws {
        try _interop.put_Title(value)
    }

    // MARK: Windows.Media.Core.IMediaCue members

    /// Gets or sets a value that specifies the duration of the chapter associated with the cue.
    /// - Returns: A value that specifies the duration of the chapter.
    public var duration: WindowsFoundation_TimeSpan {
        get throws {
            try _imediaCue.get_Duration()
        }
    }

    /// Gets or sets a value that specifies the duration of the chapter associated with the cue.
    /// - Returns: A value that specifies the duration of the chapter.
    public func duration(_ value: WindowsFoundation_TimeSpan) throws {
        try _imediaCue.put_Duration(value)
    }

    /// Gets the identifier for the timed metadata track.
    /// - Returns: The identifier for the timed metadata track.
    public var id: Swift.String {
        get throws {
            try _imediaCue.get_Id()
        }
    }

    /// Gets the identifier for the timed metadata track.
    /// - Returns: The identifier for the timed metadata track.
    public func id(_ value: Swift.String) throws {
        try _imediaCue.put_Id(value)
    }

    /// Gets the start time of the cue.
    /// - Returns: The start time of the cue.
    public var startTime: WindowsFoundation_TimeSpan {
        get throws {
            try _imediaCue.get_StartTime()
        }
    }

    /// Gets the start time of the cue.
    /// - Returns: The start time of the cue.
    public func startTime(_ value: WindowsFoundation_TimeSpan) throws {
        try _imediaCue.put_StartTime(value)
    }

    // MARK: Implementation details

    private var _imediaCue_storage: COM.COMInterop<CWinRT.SWRT_WindowsMediaCore_IMediaCue>? = nil

    internal var _imediaCue: COM.COMInterop<CWinRT.SWRT_WindowsMediaCore_IMediaCue> {
        get throws {
            try _imediaCue_storage.lazyInit {
                try _queryInterfacePointer(CWinRT.SWRT_WindowsMediaCore_IMediaCue.iid).cast(to: CWinRT.SWRT_WindowsMediaCore_IMediaCue.self)
            }
        }
    }

    deinit {
        _imediaCue_storage?.release()
    }

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.Media.Core.ChapterCue", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }
}