// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies the category of a codec.
public struct WindowsMediaCore_CodecCategory: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The codec is an encoder.
    public static let encoder = Self()

    /// The codec is a decoder.
    public static let decoder = Self(rawValue: 1)
}