// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// This class allows you to submit a set of image frames, captured in low-light settings and in close temporal proximity, and receieve a single image that has been processed to improve image lighting and fidelity.
public enum WindowsMediaCore_LowLightFusion {
    // MARK: Windows.Media.Core.ILowLightFusionStatics members

    /// Gets the maximum number of frames that can be submitted to the **FuseAsync** method.
    /// - Returns: The maximum number of frames that can be submitted to the **FuseAsync** method.
    public static var maxSupportedFrameCount: Swift.Int32 {
        get throws {
            try _ilowLightFusionStatics.get_MaxSupportedFrameCount()
        }
    }

    /// Gets a list of BitmapPixelFormat values that define the supported pixel formats for the **FuseAsync** method.
    /// - Returns: A list of supported pixel formats.
    public static var supportedBitmapPixelFormats: WindowsFoundationCollections_IVectorView<WindowsGraphicsImaging_BitmapPixelFormat> {
        get throws {
            try COM.NullResult.unwrap(_ilowLightFusionStatics.get_SupportedBitmapPixelFormats())
        }
    }

    public static func fuseAsync(_ frameSet: WindowsFoundationCollections_IIterable<WindowsGraphicsImaging_SoftwareBitmap?>?) throws -> WindowsFoundation_IAsyncOperationWithProgress<WindowsMediaCore_LowLightFusionResult?, Swift.Double> {
        try COM.NullResult.unwrap(_ilowLightFusionStatics.fuseAsync(frameSet))
    }

    // MARK: Implementation details

    private static var _ilowLightFusionStatics_storage: COM.COMInterop<CWinRT.SWRT_WindowsMediaCore_ILowLightFusionStatics>? = nil

    internal static var _ilowLightFusionStatics: COM.COMInterop<CWinRT.SWRT_WindowsMediaCore_ILowLightFusionStatics> {
        get throws {
            try _ilowLightFusionStatics_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.Media.Core.LowLightFusion", id: CWinRT.SWRT_WindowsMediaCore_ILowLightFusionStatics.iid)
            }
        }
    }
}