// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies errors related to MediaStreamSource.
public struct WindowsMediaCore_MediaStreamSourceErrorStatus: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// An unspecified error has occurred in the application.
    public static let other = Self()

    /// The application ran out of memory.
    public static let outOfMemory = Self(rawValue: 1)

    /// The application failed to open a file
    public static let failedToOpenFile = Self(rawValue: 2)

    /// The application failed to connect to a streaming media server or web server.
    public static let failedToConnectToServer = Self(rawValue: 3)

    /// The network connection to the server was lost.
    public static let connectionToServerLost = Self(rawValue: 4)

    /// An unspecified network related error has occurred.
    public static let unspecifiedNetworkError = Self(rawValue: 5)

    /// The application encountered an error while attempting to decode the media data.
    public static let decodeError = Self(rawValue: 6)

    /// The application does not support the media storage format or media encoding format.
    public static let unsupportedMediaFormat = Self(rawValue: 7)
}