// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Defines values that specify whether the brush samples from the app content or from the content behind the app window.
public struct WindowsUIXamlMedia_AcrylicBackgroundSource: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The brush samples from the content behind the app window.
    public static let hostBackdrop = Self()

    /// The brush samples from the app content.
    public static let backdrop = Self(rawValue: 1)
}