// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Defines the potential states of a MediaElement object.
public struct WindowsUIXamlMedia_MediaElementState: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The MediaElement contains no media. The MediaElement displays a transparent frame.
    public static let closed = Self()

    /// The MediaElement is validating and attempting to load the specified source.
    public static let opening = Self(rawValue: 1)

    /// The MediaElement is loading the media for playback. Its Position does not advance during this state. If the MediaElement was already playing video, it continues to display the last displayed frame.
    public static let buffering = Self(rawValue: 2)

    /// The MediaElement is playing the current media source.
    public static let playing = Self(rawValue: 3)

    /// The MediaElement does not advance its Position. If the MediaElement was playing video, it continues to display the current frame.
    public static let paused = Self(rawValue: 4)

    /// The MediaElement contains media but is not playing or paused. Its Position is 0 and does not advance. If the loaded media is video, the MediaElement displays the first frame.
    public static let stopped = Self(rawValue: 5)
}