// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Describes the simulation style of a font.
public struct WindowsUIXamlMedia_StyleSimulations: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// No font style simulation.
    public static let none = Self()

    /// Bold style simulation.
    public static let boldSimulation = Self(rawValue: 1)

    /// Italic style simulation.
    public static let italicSimulation = Self(rawValue: 2)

    /// Bold and italic style simulation.
    public static let boldItalicSimulation = Self(rawValue: 3)
}