// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the method that will handle the Holding event.
/// - Parameter sender: The object where the event handler is attached.
/// - Parameter e: Event data for the event.
public typealias WindowsUIXamlInput_HoldingEventHandler = (WindowsRuntime.IInspectable?, WindowsUIXamlInput_HoldingRoutedEventArgs?) throws -> Swift.Void