// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Indicates the current state of a GeofenceMonitor.
public struct WindowsDevicesGeolocationGeofencing_GeofenceMonitorStatus: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The monitor is ready and active.
    public static let ready = Self()

    /// The monitor is in the process of initializing.
    public static let initializing = Self(rawValue: 1)

    /// There is no data on the status of the monitor.
    public static let noData = Self(rawValue: 2)

    /// Access to location is denied.
    public static let disabled = Self(rawValue: 3)

    /// The geofence monitor has not been initialized.
    public static let notInitialized = Self(rawValue: 4)

    /// The geofence monitor is not available.
    public static let notAvailable = Self(rawValue: 5)
}