// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies how the InkPresenter object handles input (standard and modified) from the associated InkCanvas control when system is in high contrast mode.
public struct WindowsUIInputInking_InkHighContrastAdjustment: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// For standard strokes, use selected color if contrast is sufficient against the background. Otherwise, use system color.
    public static let useSystemColorsWhenNecessary = Self()

    /// For standard strokes, use system color.
    public static let useSystemColors = Self(rawValue: 1)

    /// For standard strokes, use the selected color.
    public static let useOriginalColors = Self(rawValue: 2)
}