// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Contains event data for the StrokesErased event of the InkPresenter associated with an InkCanvas control.
public final class WindowsUIInputInking_InkStrokesErasedEventArgs: WindowsRuntime.WinRTImport<WindowsUIInputInking_InkStrokesErasedEventArgsProjection> {
    // MARK: Windows.UI.Input.Inking.IInkStrokesErasedEventArgs members

    /// Gets the collection of ink strokes associated with the StrokesErased event.
    /// - Returns: The erased ink strokes as a collection of InkStroke objects.
    public var strokes: WindowsFoundationCollections_IVectorView<WindowsUIInputInking_InkStroke?> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Strokes())
        }
    }

    // MARK: Implementation details
}