// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Identifies the shape of the PenTip.
public struct WindowsUIInputInking_PenTipShape: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Circular or elliptical pen tip. Use Size to specify the dimensions.
    public static let circle = Self()

    /// Square or rectangular pen tip. Use Size to specify the dimensions.
    public static let rectangle = Self(rawValue: 1)
}