// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Defines the advanced photo capture modes.
public struct WindowsMediaDevices_AdvancedPhotoMode: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The system dynamically determines the advanced photo capture mode.
    public static let auto = Self()

    /// Standard capture mode.
    public static let standard = Self(rawValue: 1)

    /// High Dynamic Range (HDR) capture mode.
    public static let hdr = Self(rawValue: 2)

    /// Low light capture mode.
    public static let lowLight = Self(rawValue: 3)
}