// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides information about the activated event that fires when an app is used to search.
public protocol WindowsApplicationModelActivation_ISearchActivatedEventArgsProtocol: WindowsApplicationModelActivation_IActivatedEventArgsProtocol {
    /// The Internet Engineering Task Force (IETF) language tag (BCP 47 standard) that identifies the language currently associated with the user's text input device.
    /// - Returns: The Internet Engineering Task Force (IETF) BCP 47 standard language tag.
    var language: Swift.String { get throws }

    /// The text that the user wants the app to search for. The user entered this text into the search box of the search pane.
    /// - Returns: The text to find.
    var queryText: Swift.String { get throws }
}

/// Provides information about the activated event that fires when an app is used to search.
public typealias WindowsApplicationModelActivation_ISearchActivatedEventArgs = any WindowsApplicationModelActivation_ISearchActivatedEventArgsProtocol