// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Displays the UI that lets users download maps for offline use, or update maps that were previously downloaded.
public enum WindowsServicesMaps_MapManager {
    // MARK: Windows.Services.Maps.IMapManagerStatics members

    /// Displays the UI that lets users download maps for offline use.
    public static func showDownloadedMapsUI() throws {
        try _imapManagerStatics.showDownloadedMapsUI()
    }

    /// Displays the UI that lets users update maps that were previously downloaded for offline use.
    public static func showMapsUpdateUI() throws {
        try _imapManagerStatics.showMapsUpdateUI()
    }

    // MARK: Implementation details

    private static var _imapManagerStatics_storage: COM.COMInterop<CWinRT.SWRT_WindowsServicesMaps_IMapManagerStatics>? = nil

    internal static var _imapManagerStatics: COM.COMInterop<CWinRT.SWRT_WindowsServicesMaps_IMapManagerStatics> {
        get throws {
            try _imapManagerStatics_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.Services.Maps.MapManager", id: CWinRT.SWRT_WindowsServicesMaps_IMapManagerStatics.iid)
            }
        }
    }
}