// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Identifies the state of the dialog box option on whether to save credentials.
public struct WindowsSecurityCredentialsUI_CredentialSaveOption: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The "Save credentials?" dialog box is not selected, indicating that the user doesn't want their credentials saved.
    public static let unselected = Self()

    /// The "Save credentials?" dialog box is selected, indicating that the user wants their credentials saved.
    public static let selected = Self(rawValue: 1)

    /// The "Save credentials?" dialog box is not displayed at all.
    public static let hidden = Self(rawValue: 2)
}