// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Base class for graphics effect sources.
public protocol WindowsGraphicsEffects_IGraphicsEffectSourceProtocol: IInspectableProtocol {
}

/// Base class for graphics effect sources.
public typealias WindowsGraphicsEffects_IGraphicsEffectSource = any WindowsGraphicsEffects_IGraphicsEffectSourceProtocol