// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Holds information about the content that the current session has.
public final class WindowsMediaControl_GlobalSystemMediaTransportControlsSessionMediaProperties: WindowsRuntime.WinRTImport<WindowsMediaControl_GlobalSystemMediaTransportControlsSessionMediaPropertiesProjection> {
    // MARK: Windows.Media.Control.IGlobalSystemMediaTransportControlsSessionMediaProperties members

    /// Gets the album's artist
    /// - Returns: The name of the album artist.
    public var albumArtist: Swift.String {
        get throws {
            try _interop.get_AlbumArtist()
        }
    }

    /// Gets the title of the album.
    /// - Returns: The title of the album.
    public var albumTitle: Swift.String {
        get throws {
            try _interop.get_AlbumTitle()
        }
    }

    /// Gets the total number of tracks on the album.
    /// - Returns: The total number of tracks on the album.
    public var albumTrackCount: Swift.Int32 {
        get throws {
            try _interop.get_AlbumTrackCount()
        }
    }

    /// Gets the Artist's name.
    /// - Returns: The Artist name.
    public var artist: Swift.String {
        get throws {
            try _interop.get_Artist()
        }
    }

    /// Gets the list of genres.
    /// - Returns: A list of all strings representing the genres.
    public var genres: WindowsFoundationCollections_IVectorView<Swift.String> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Genres())
        }
    }

    /// The playback type of the content
    /// - Returns: The type of media.
    public var playbackType: WindowsFoundation_IReference<WindowsMedia_MediaPlaybackType>? {
        get throws {
            try _interop.get_PlaybackType()
        }
    }

    /// Gets the subtitle.
    /// - Returns: The subtitle of the media.
    public var subtitle: Swift.String {
        get throws {
            try _interop.get_Subtitle()
        }
    }

    /// A reference to a RandomAccessStream of the thumbnail image associated with this content.
    /// - Returns: The thumbnail image.
    public var thumbnail: WindowsStorageStreams_IRandomAccessStreamReference {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Thumbnail())
        }
    }

    /// Gets the title.
    /// - Returns: The title.
    public var title: Swift.String {
        get throws {
            try _interop.get_Title()
        }
    }

    /// The number associated with this track
    /// - Returns: The track number.
    public var trackNumber: Swift.Int32 {
        get throws {
            try _interop.get_TrackNumber()
        }
    }

    // MARK: Implementation details
}