// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents arguments for a MediaPropertiesChanged event.
public final class WindowsMediaControl_MediaPropertiesChangedEventArgs: WindowsRuntime.WinRTImport<WindowsMediaControl_MediaPropertiesChangedEventArgsProjection> {
    // MARK: Implementation details
}