// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Defines properties for web account provider token objects that are retrieved in the context of a specific user.
public protocol WindowsSecurityAuthenticationWebProvider_IWebAccountProviderTokenObjects2Protocol: WindowsSecurityAuthenticationWebProvider_IWebAccountProviderTokenObjectsProtocol {
    /// Gets the user for this token objects set.
    /// - Returns: The user for this token objects set.
    var user: WindowsSystem_User { get throws }
}

/// Defines properties for web account provider token objects that are retrieved in the context of a specific user.
public typealias WindowsSecurityAuthenticationWebProvider_IWebAccountProviderTokenObjects2 = any WindowsSecurityAuthenticationWebProvider_IWebAccountProviderTokenObjects2Protocol