// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Describes an error on a Play To connection.
public struct WindowsMediaPlayTo_PlayToConnectionError: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// No error occurred.
    public static let none = Self()

    /// The Play To target device has not responded for at least 5 seconds.
    public static let deviceNotResponding = Self(rawValue: 1)

    /// The Play To target device has encountered an error.
    public static let deviceError = Self(rawValue: 2)

    /// The Play To target device is locked.
    public static let deviceLocked = Self(rawValue: 3)

    /// The Play To target device failed to play the protected content.
    public static let protectedPlaybackFailed = Self(rawValue: 4)
}