// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides an application's name, description, and logo
public final class WindowsApplicationModel_AppDisplayInfo: WindowsRuntime.WinRTImport<WindowsApplicationModel_AppDisplayInfoProjection> {
    // MARK: Windows.ApplicationModel.IAppDisplayInfo members

    /// Gets the application's description.
    /// - Returns: The description of the application as defined in the package manifest (Package.appxmanifest).
    public var description: Swift.String {
        get throws {
            try _interop.get_Description()
        }
    }

    /// Gets the application's display name.
    /// - Returns: The display name of the application as defined in the package manifest (Package.appxmanifest).
    public var displayName: Swift.String {
        get throws {
            try _interop.get_DisplayName()
        }
    }

    /// Get the application's logo.
    /// - Parameter size: The size of the rectangle in which the logo must fit.
    /// - Returns: The largest logo in your Package.appxmanifest file that will fit in the specified *Size*.
    public func getLogo(_ size: WindowsFoundation_Size) throws -> WindowsStorageStreams_RandomAccessStreamReference {
        try COM.NullResult.unwrap(_interop.getLogo(size))
    }

    // MARK: Implementation details
}