// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the package version info.
public struct WindowsApplicationModel_PackageVersion: Hashable, Codable {
    /// The major version number of the package.
    public var major: Swift.UInt16

    /// The minor version number of the package.
    public var minor: Swift.UInt16

    /// The build version number of the package.
    public var build: Swift.UInt16

    /// The revision version number of the package.
    public var revision: Swift.UInt16

    public init() {
        self.major = 0
        self.minor = 0
        self.build = 0
        self.revision = 0
    }

    public init(major: Swift.UInt16, minor: Swift.UInt16, build: Swift.UInt16, revision: Swift.UInt16) {
        self.major = major
        self.minor = minor
        self.build = build
        self.revision = revision
    }
}