// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies the priority of the task.
public struct WindowsApplicationModelUserDataTasks_UserDataTaskPriority: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The task has the normal priority.
    public static let normal = Self()

    /// The task is a low priority.
    public static let low = Self(rawValue: -1)

    /// The task is a high priority.
    public static let high = Self(rawValue: 1)
}