// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a display request.
public final class WindowsSystemDisplay_DisplayRequest: WindowsRuntime.WinRTImport<WindowsSystemDisplay_DisplayRequestProjection> {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsSystemDisplay_DisplayRequestProjection.self))
    }

    // MARK: Windows.System.Display.IDisplayRequest members

    /// Activates a display request.
    public func requestActive() throws {
        try _interop.requestActive()
    }

    /// Deactivates a display request.
    public func requestRelease() throws {
        try _interop.requestRelease()
    }

    // MARK: Implementation details

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.System.Display.DisplayRequest", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }
}