// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Manages delayed navigation for an app.
public final class WindowsUIWebUI_WebUINavigatedDeferral: WindowsRuntime.WinRTImport<WindowsUIWebUI_WebUINavigatedDeferralProjection> {
    // MARK: Windows.UI.WebUI.IWebUINavigatedDeferral members

    /// Notifies the system that the app has set up its state and UI and is ready to be displayed after a top level navigation.
    public func complete() throws {
        try _interop.complete()
    }

    // MARK: Implementation details
}