// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies which tab to display on a mini contact card.
public struct WindowsApplicationModelContacts_ContactCardTabKind: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The default tab.
    public static let `default` = Self()

    /// The email tab.
    public static let email = Self(rawValue: 1)

    /// The messaging tab.
    public static let messaging = Self(rawValue: 2)

    /// The phone tab.
    public static let phone = Self(rawValue: 3)

    /// The video tab.
    public static let video = Self(rawValue: 4)

    /// The organizational hierarchy tab.
    public static let organizationalHierarchy = Self(rawValue: 5)
}