// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides a way to tag existing user contacts with additional information, specifying that your app can perform some SupportedOperations for this particular contact.
public final class WindowsApplicationModelContacts_ContactAnnotation: WindowsRuntime.WinRTImport<WindowsApplicationModelContacts_ContactAnnotationProjection> {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsApplicationModelContacts_ContactAnnotationProjection.self))
    }

    // MARK: Windows.ApplicationModel.Contacts.IContactAnnotation members

    /// Gets the ID for the parent ContactAnnotationList that this ContactAnnotation is contained within.
    /// - Returns: The ID for the parent ContactAnnotationList that this ContactAnnotation is contained within.
    public var annotationListId: Swift.String {
        get throws {
            try _interop.get_AnnotationListId()
        }
    }

    /// Gets or set the ID for the Contact to which this ContactAnnotation applies.
    /// - Returns: The ID for the Contact to which this ContactAnnotation applies.
    public var contactId: Swift.String {
        get throws {
            try _interop.get_ContactId()
        }
    }

    /// Gets or set the ID for the Contact to which this ContactAnnotation applies.
    /// - Returns: The ID for the Contact to which this ContactAnnotation applies.
    public func contactId(_ value: Swift.String) throws {
        try _interop.put_ContactId(value)
    }

    /// Gets the ID for this ContactAnnotation.
    /// - Returns: The ID for this ContactAnnotation.
    public var id: Swift.String {
        get throws {
            try _interop.get_Id()
        }
    }

    /// Gets a Boolean value indicating if this ContactAnnotation has been disabled by the user.
    /// - Returns: Boolean value indicating if this ContactAnnotation has been disabled by the user.
    public var isDisabled: Swift.Bool {
        get throws {
            try _interop.get_IsDisabled()
        }
    }

    /// Provides a place to store data to be used by the app when interacting with a service provider.
    /// - Returns: Data to be used by the app when interacting with a service provider.
    public var providerProperties: WindowsFoundationCollections_ValueSet {
        get throws {
            try COM.NullResult.unwrap(_interop.get_ProviderProperties())
        }
    }

    /// Gets or sets an ID that can be used by a service provider to access the corresponding entity in their remote system.
    /// - Returns: An ID that can be used by a service provider to access the corresponding entity in their remote system.
    public var remoteId: Swift.String {
        get throws {
            try _interop.get_RemoteId()
        }
    }

    /// Gets or sets an ID that can be used by a service provider to access the corresponding entity in their remote system.
    /// - Returns: An ID that can be used by a service provider to access the corresponding entity in their remote system.
    public func remoteId(_ value: Swift.String) throws {
        try _interop.put_RemoteId(value)
    }

    /// Gets or sets the group of ContactAnnotationOperations supported by this ContactAnnotation.
    /// - Returns: The group of ContactAnnotationOperations supported by this ContactAnnotation.
    public var supportedOperations: WindowsApplicationModelContacts_ContactAnnotationOperations {
        get throws {
            try _interop.get_SupportedOperations()
        }
    }

    /// Gets or sets the group of ContactAnnotationOperations supported by this ContactAnnotation.
    /// - Returns: The group of ContactAnnotationOperations supported by this ContactAnnotation.
    public func supportedOperations(_ value: WindowsApplicationModelContacts_ContactAnnotationOperations) throws {
        try _interop.put_SupportedOperations(value)
    }

    // MARK: Windows.ApplicationModel.Contacts.IContactAnnotation2 members

    /// Gets or sets the ContactList to which this ContactAnnotation applies.
    /// - Returns: The ID for the ContactList to which this ContactAnnotation applies.
    public var contactListId: Swift.String {
        get throws {
            try _icontactAnnotation2.get_ContactListId()
        }
    }

    /// Gets or sets the ContactList to which this ContactAnnotation applies.
    /// - Returns: The ID for the ContactList to which this ContactAnnotation applies.
    public func contactListId(_ value: Swift.String) throws {
        try _icontactAnnotation2.put_ContactListId(value)
    }

    // MARK: Implementation details

    private var _icontactAnnotation2_storage: COM.COMInterop<CWinRT.SWRT_WindowsApplicationModelContacts_IContactAnnotation2>? = nil

    internal var _icontactAnnotation2: COM.COMInterop<CWinRT.SWRT_WindowsApplicationModelContacts_IContactAnnotation2> {
        get throws {
            try _icontactAnnotation2_storage.lazyInit {
                try _queryInterfacePointer(CWinRT.SWRT_WindowsApplicationModelContacts_IContactAnnotation2.iid).cast(to: CWinRT.SWRT_WindowsApplicationModelContacts_IContactAnnotation2.self)
            }
        }
    }

    deinit {
        _icontactAnnotation2_storage?.release()
    }

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.ApplicationModel.Contacts.ContactAnnotation", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }
}