// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides operations that an app can perform on a contact list that it has not created.
public final class WindowsApplicationModelContacts_ContactListLimitedWriteOperations: WindowsRuntime.WinRTImport<WindowsApplicationModelContacts_ContactListLimitedWriteOperationsProjection> {
    // MARK: Windows.ApplicationModel.Contacts.IContactListLimitedWriteOperations members

    /// Asynchronously attempts to create or update a contact.
    /// - Parameter contact: The contact to create or update.
    /// - Returns: A Boolean value indicating if the operation was successful.
    public func tryCreateOrUpdateContactAsync(_ contact: WindowsApplicationModelContacts_Contact?) throws -> WindowsFoundation_IAsyncOperation<Swift.Bool> {
        try COM.NullResult.unwrap(_interop.tryCreateOrUpdateContactAsync(contact))
    }

    /// Asynchronously attempts to delete a contact.
    /// - Parameter contactId: The ID of the contact to delete.
    /// - Returns: A Boolean value indicating if the operation was successful.
    public func tryDeleteContactAsync(_ contactId: Swift.String) throws -> WindowsFoundation_IAsyncOperation<Swift.Bool> {
        try COM.NullResult.unwrap(_interop.tryDeleteContactAsync(contactId))
    }

    // MARK: Implementation details
}