// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies the options for displaying the full contact card.
public final class WindowsApplicationModelContacts_FullContactCardOptions: WindowsRuntime.WinRTImport<WindowsApplicationModelContacts_FullContactCardOptionsProjection> {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsApplicationModelContacts_FullContactCardOptionsProjection.self))
    }

    // MARK: Windows.ApplicationModel.Contacts.IFullContactCardOptions members

    /// Gets or sets a value that describes the desired view size for the full contact card.
    /// - Returns: A value that describes the desired view size for the full contact card.
    public var desiredRemainingView: WindowsUIViewManagement_ViewSizePreference {
        get throws {
            try _interop.get_DesiredRemainingView()
        }
    }

    /// Gets or sets a value that describes the desired view size for the full contact card.
    /// - Returns: A value that describes the desired view size for the full contact card.
    public func desiredRemainingView(_ value: WindowsUIViewManagement_ViewSizePreference) throws {
        try _interop.put_DesiredRemainingView(value)
    }

    // MARK: Implementation details

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.ApplicationModel.Contacts.FullContactCardOptions", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }
}