// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Enables an app to share a file with another app by passing a token via Uri activation, app service, REST API, etc. The target app redeems the token to get the file shared by the source app.
public enum WindowsApplicationModelDataTransfer_SharedStorageAccessManager {
    // MARK: Windows.ApplicationModel.DataTransfer.ISharedStorageAccessManagerStatics members

    /// Gets the sharing token that enables an app to share the specified file with another app.
    /// - Parameter file: The file to share with the target app.
    /// - Returns: The sharing token to provide to the target app .
    public static func addFile(_ file: WindowsStorage_IStorageFile?) throws -> Swift.String {
        try _isharedStorageAccessManagerStatics.addFile(file)
    }

    /// Gets a file shared by another app by providing the sharing token received from the source app.
    /// - Parameter token: The sharing token for the shared file.
    /// - Returns: A wrapper object that contains the shared file.
    public static func redeemTokenForFileAsync(_ token: Swift.String) throws -> WindowsFoundation_IAsyncOperation<WindowsStorage_StorageFile?> {
        try COM.NullResult.unwrap(_isharedStorageAccessManagerStatics.redeemTokenForFileAsync(token))
    }

    /// Revokes an existing sharing token.
    /// - Parameter token: The sharing token to revoke.
    public static func removeFile(_ token: Swift.String) throws {
        try _isharedStorageAccessManagerStatics.removeFile(token)
    }

    // MARK: Implementation details

    private static var _isharedStorageAccessManagerStatics_storage: COM.COMInterop<CWinRT.SWRT_WindowsApplicationModelDataTransfer_ISharedStorageAccessManagerStatics>? = nil

    internal static var _isharedStorageAccessManagerStatics: COM.COMInterop<CWinRT.SWRT_WindowsApplicationModelDataTransfer_ISharedStorageAccessManagerStatics> {
        get throws {
            try _isharedStorageAccessManagerStatics_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.ApplicationModel.DataTransfer.SharedStorageAccessManager", id: CWinRT.SWRT_WindowsApplicationModelDataTransfer_ISharedStorageAccessManagerStatics.iid)
            }
        }
    }
}