// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Indicates the altitude reference system to be used in defining a geographic shape.
public struct WindowsDevicesGeolocation_AltitudeReferenceSystem: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The altitude reference system was not specified.
    public static let unspecified = Self()

    /// The altitude reference system is based on distance above terrain or ground level.
    public static let terrain = Self(rawValue: 1)

    /// The altitude reference system is based on an ellipsoid which is a mathematical approximation of the shape of the Earth.
    public static let ellipsoid = Self(rawValue: 2)

    /// The altitude reference system is based on the distance above sea level.
    public static let geoid = Self(rawValue: 3)

    /// The altitude reference system is based on the distance above the tallest surface structures, such as buildings, trees, roads, etc., above terrain or ground level.
    public static let surface = Self(rawValue: 4)
}