// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Indicates the ability of the Geolocator object to provide location data.
public struct WindowsDevicesGeolocation_PositionStatus: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Location data is available.
    public static let ready = Self()

    /// Location services is initializing. This is the status if a GPS is the source of location data and the GPS receiver does not yet have the required number of satellites in view to obtain an accurate position.
    public static let initializing = Self(rawValue: 1)

    /// No location data is available from any source. LocationStatus will have this value if the application calls GetGeopositionAsync or registers an event handler for the PositionChanged event, before data is available from a location sensor. Once data is available LocationStatus transitions to the **Ready** state.
    public static let noData = Self(rawValue: 2)

    /// Location settings are turned off. This status indicates that the user has not granted the application permission to access location.
    public static let disabled = Self(rawValue: 3)

    /// An operation to retrieve location has not yet been initialized. LocationStatus will have this value if the application has not yet called GetGeopositionAsync or registered an event handler for the PositionChanged event. LocationStatus may also have this value if your app doesn’t have permission to access location.
    public static let notInitialized = Self(rawValue: 4)

    /// Location services is not available on this version of Windows.
    public static let notAvailable = Self(rawValue: 5)
}