// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Contains event data for the AutoHideScrollBarsChanged event.
public final class WindowsUIViewManagement_UISettingsAutoHideScrollBarsChangedEventArgs: WindowsRuntime.WinRTImport<WindowsUIViewManagement_UISettingsAutoHideScrollBarsChangedEventArgsProjection> {
    // MARK: Implementation details
}