// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a reusable hashing object and contains the result of a hashing operation.
public final class WindowsSecurityCryptographyCore_CryptographicHash: WindowsRuntime.WinRTImport<WindowsSecurityCryptographyCore_CryptographicHashProjection> {
    // MARK: Windows.Security.Cryptography.Core.IHashComputation members

    /// Appends a binary encoded string to the data stored in the CryptographicHash object.
    /// - Parameter data: Data to append.
    public func append(_ data: WindowsStorageStreams_IBuffer?) throws {
        try _interop.append(data)
    }

    /// Gets hashed data from the CryptographicHash object and resets the object.
    /// - Returns: Hashed data.
    public func getValueAndReset() throws -> WindowsStorageStreams_IBuffer {
        try COM.NullResult.unwrap(_interop.getValueAndReset())
    }

    // MARK: Implementation details
}