// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides access to the feedback behaviors supported by the haptic input device.
public final class WindowsDevicesHaptics_SimpleHapticsControllerFeedback: WindowsRuntime.WinRTImport<WindowsDevicesHaptics_SimpleHapticsControllerFeedbackProjection> {
    // MARK: Windows.Devices.Haptics.ISimpleHapticsControllerFeedback members

    /// Gets the feedback duration for the haptic input device.
    /// - Returns: The time period, expressed in 100-nanosecond units.
    public var duration: WindowsFoundation_TimeSpan {
        get throws {
            try _interop.get_Duration()
        }
    }

    /// Gets the haptic waveform type for the haptic input device.
    /// - Returns: An unsigned 16-bit waveform ID (based on the Haptic Usage Page HID specification.
    public var waveform: Swift.UInt16 {
        get throws {
            try _interop.get_Waveform()
        }
    }

    // MARK: Implementation details
}