// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a source of log messages.
public protocol WindowsFoundationDiagnostics_ILoggingChannelProtocol: WindowsFoundation_IClosableProtocol {
    /// Gets a value that indicates whether messages are being logged on the current LoggingChannel.
    /// - Returns: **True** if messages are being logged on the current channel; otherwise, **false**.
    var enabled: Swift.Bool { get throws }

    /// Gets the level of detail for messages from the current LoggingChannel.
    /// - Returns: The level of detail for messages.
    var level: WindowsFoundationDiagnostics_LoggingLevel { get throws }

    /// Gets the name of the current LoggingChannel.
    /// - Returns: The name.
    var name: Swift.String { get throws }

    /// Raised when the logging channel is attached to a LoggingSession or other event tracing and debugging tools.
    func loggingEnabled(adding handler: WindowsFoundation_TypedEventHandler<WindowsFoundationDiagnostics_ILoggingChannel?, WindowsRuntime.IInspectable?>?) throws -> WindowsRuntime.EventRegistration
    func loggingEnabled(removing token: WindowsRuntime.EventRegistrationToken) throws

    /// Logs a message to the current LoggingChannel.
    /// - Parameter eventString: The message to log.
    func logMessage(_ eventString: Swift.String) throws

    /// Logs a message to the current LoggingChannel with the specified LoggingLevel.
    /// - Parameter eventString: The message to log.
    /// - Parameter level: The logging level.
    func logMessage(_ eventString: Swift.String, _ level: WindowsFoundationDiagnostics_LoggingLevel) throws

    /// Logs data to the current LoggingChannel.
    /// - Parameter value1: The string to associate with *value2*.
    /// - Parameter value2: The value to associate with *value1*.
    func logValuePair(_ value1: Swift.String, _ value2: Swift.Int32) throws

    /// Logs data to the current LoggingChannel with the specified LoggingLevel.
    /// - Parameter value1: The string to associate with *value2*.
    /// - Parameter value2: The value to associate with *value1*.
    /// - Parameter level: The logging level.
    func logValuePair(_ value1: Swift.String, _ value2: Swift.Int32, _ level: WindowsFoundationDiagnostics_LoggingLevel) throws
}

/// Represents a source of log messages.
public typealias WindowsFoundationDiagnostics_ILoggingChannel = any WindowsFoundationDiagnostics_ILoggingChannelProtocol