// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the result of the creation of a AdaptiveMediaSource object.
public final class WindowsMediaStreamingAdaptive_AdaptiveMediaSourceCreationResult: WindowsRuntime.WinRTImport<WindowsMediaStreamingAdaptive_AdaptiveMediaSourceCreationResultProjection> {
    // MARK: Windows.Media.Streaming.Adaptive.IAdaptiveMediaSourceCreationResult members

    /// Gets the HTTP response message, if any, returned from an attempt to create a AdaptiveMediaSource object.
    /// - Returns: The HTTP response message returned from an attempt to create a AdaptiveMediaSource object.
    public var httpResponseMessage: WindowsWebHttp_HttpResponseMessage {
        get throws {
            try COM.NullResult.unwrap(_interop.get_HttpResponseMessage())
        }
    }

    /// Gets the AdaptiveMediaSource object that represents the source of adaptive streaming content.
    /// - Returns: The AdaptiveMediaSource object that represents the source of adaptive streaming content.
    public var mediaSource: WindowsMediaStreamingAdaptive_AdaptiveMediaSource {
        get throws {
            try COM.NullResult.unwrap(_interop.get_MediaSource())
        }
    }

    /// Gets the status of an attempt to create a AdaptiveMediaSource object.
    /// - Returns: A AdaptiveMediaSourceCreationStatus -typed value that specifies the result of an attempt to create a AdaptiveMediaSource object.
    public var status: WindowsMediaStreamingAdaptive_AdaptiveMediaSourceCreationStatus {
        get throws {
            try _interop.get_Status()
        }
    }

    // MARK: Windows.Media.Streaming.Adaptive.IAdaptiveMediaSourceCreationResult2 members

    /// Gets the extended error code associated with the creation of a AdaptiveMediaSource object.
    /// - Returns: The extended error code associated with the creation of a AdaptiveMediaSource object.
    public var extendedError: COM.HResult {
        get throws {
            try _iadaptiveMediaSourceCreationResult2.get_ExtendedError()
        }
    }

    // MARK: Implementation details

    private var _iadaptiveMediaSourceCreationResult2_storage: COM.COMInterop<CWinRT.SWRT_WindowsMediaStreamingAdaptive_IAdaptiveMediaSourceCreationResult2>? = nil

    internal var _iadaptiveMediaSourceCreationResult2: COM.COMInterop<CWinRT.SWRT_WindowsMediaStreamingAdaptive_IAdaptiveMediaSourceCreationResult2> {
        get throws {
            try _iadaptiveMediaSourceCreationResult2_storage.lazyInit {
                try _queryInterfacePointer(CWinRT.SWRT_WindowsMediaStreamingAdaptive_IAdaptiveMediaSourceCreationResult2.iid).cast(to: CWinRT.SWRT_WindowsMediaStreamingAdaptive_IAdaptiveMediaSourceCreationResult2.self)
            }
        }
    }

    deinit {
        _iadaptiveMediaSourceCreationResult2_storage?.release()
    }
}