// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies the result of an attempt to create a AdaptiveMediaSource object.
public struct WindowsMediaStreamingAdaptive_AdaptiveMediaSourceCreationStatus: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The AdaptiveMediaSource object was successfully created.
    public static let success = Self()

    /// The creation of the AdaptiveMediaSource object failed as the result of a failure in downloading the adaptive streaming manifest.
    public static let manifestDownloadFailure = Self(rawValue: 1)

    /// The creation of the AdaptiveMediaSource object failed as the result of a failure in parsing the adaptive streaming manifest.
    public static let manifestParseFailure = Self(rawValue: 2)

    /// The creation of the AdaptiveMediaSource object failed because the content of the adaptive streaming manifest is unsupported.
    public static let unsupportedManifestContentType = Self(rawValue: 3)

    /// The creation of the AdaptiveMediaSource object failed because the version of the adaptive streaming manifest is unsupported.
    public static let unsupportedManifestVersion = Self(rawValue: 4)

    /// The creation of the AdaptiveMediaSource object failed because the profile of the adaptive streaming manifest is unsupported.
    public static let unsupportedManifestProfile = Self(rawValue: 5)

    /// The creation of the AdaptiveMediaSource object failed because of an unknown failure.
    public static let unknownFailure = Self(rawValue: 6)
}