// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides calculated values that can be referenced as **TemplatedParent** sources when defining templates for a SplitView. Not intended for general use.
public final class WindowsUIXamlControlsPrimitives_SplitViewTemplateSettings: WindowsRuntime.WinRTImport<WindowsUIXamlControlsPrimitives_SplitViewTemplateSettingsProjection> {
    // MARK: Windows.UI.Xaml.Controls.Primitives.ISplitViewTemplateSettings members

    /// Gets the CompactPaneLength value as a GridLength.
    /// - Returns: The CompactPaneLength value as a GridLength.
    public var compactPaneGridLength: WindowsUIXaml_GridLength {
        get throws {
            try _interop.get_CompactPaneGridLength()
        }
    }

    /// Gets the negative of the OpenPaneLength value.
    /// - Returns: The negative of the OpenPaneLength value.
    public var negativeOpenPaneLength: Swift.Double {
        get throws {
            try _interop.get_NegativeOpenPaneLength()
        }
    }

    /// Gets the negative of the value calculated by subtracting the CompactPaneLength value from the OpenPaneLength value.
    /// - Returns: The negative of the OpenPaneLength value minus the CompactPaneLength value.
    public var negativeOpenPaneLengthMinusCompactLength: Swift.Double {
        get throws {
            try _interop.get_NegativeOpenPaneLengthMinusCompactLength()
        }
    }

    /// Gets the OpenPaneLength value as a GridLength.
    /// - Returns: The OpenPaneLength value as a GridLength.
    public var openPaneGridLength: WindowsUIXaml_GridLength {
        get throws {
            try _interop.get_OpenPaneGridLength()
        }
    }

    /// Gets the OpenPaneLength value.
    /// - Returns: The OpenPaneLength value.
    public var openPaneLength: Swift.Double {
        get throws {
            try _interop.get_OpenPaneLength()
        }
    }

    /// Gets a value calculated by subtracting the CompactPaneLength value from the OpenPaneLength value.
    /// - Returns: The value calculated by subtracting the CompactPaneLength value from the OpenPaneLength value.
    public var openPaneLengthMinusCompactLength: Swift.Double {
        get throws {
            try _interop.get_OpenPaneLengthMinusCompactLength()
        }
    }

    // MARK: Implementation details
}