// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies the read options for an input stream.
public struct WindowsStorageStreams_InputStreamOptions: OptionSet, Hashable, Codable {
    public var rawValue: Swift.UInt32

    public init(rawValue: Swift.UInt32 = 0) {
        self.rawValue = rawValue
    }

    /// No options are specified.
    public static let none = Self()

    /// The asynchronous read operation completes when one or more bytes is available.
    public static let partial = Self(rawValue: 1)

    /// The asynchronous read operation may optionally read ahead and prefetch additional bytes.
    public static let readAhead = Self(rawValue: 2)
}