// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides information about the focus capabilities of the capture device for frames in a variable photo sequences.
public final class WindowsMediaDevicesCore_FrameFocusCapabilities: WindowsRuntime.WinRTImport<WindowsMediaDevicesCore_FrameFocusCapabilitiesProjection> {
    // MARK: Windows.Media.Devices.Core.IFrameFocusCapabilities members

    /// Gets the maximum focus length supported by the capture device for a frame in a variable photo sequence, specified in millimeters.
    /// - Returns: The maximum focus length supported by the capture device for a frame in a variable photo sequence.
    public var max: Swift.UInt32 {
        get throws {
            try _interop.get_Max()
        }
    }

    /// Gets the minimum focus length supported by the capture device for a frame in a variable photo sequence, specified in millimeters.
    /// - Returns: The minimum focus length supported by the capture device for a frame in a variable photo sequence.
    public var min: Swift.UInt32 {
        get throws {
            try _interop.get_Min()
        }
    }

    /// Gets the smallest focus increment supported by the capture device for a frame in a variable photo sequence, specified in millimeters.
    /// - Returns: The smallest focus increment supported by the capture device for a frame in a variable photo sequence.
    public var step: Swift.UInt32 {
        get throws {
            try _interop.get_Step()
        }
    }

    /// Gets a value that indicates if the capture device supports the focus control for frames in a variable photo sequence.
    /// - Returns: True if the capture device supports the focus control; otherwise, false.
    public var supported: Swift.Bool {
        get throws {
            try _interop.get_Supported()
        }
    }

    // MARK: Implementation details
}