// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Indicates the link type of a range of text.
public struct WindowsUIText_LinkType: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// A mix of link and nonlink attributes.
    public static let undefined = Self()

    /// Not a link.
    public static let notALink = Self(rawValue: 1)

    /// A link specified by the client; that is, not an autolink or a friendly-name link.
    public static let clientLink = Self(rawValue: 2)

    /// The name part of a friendly-name link. The name is the part that is displayed.
    public static let friendlyLinkName = Self(rawValue: 3)

    /// The address Uniform Resource Identifier (URI) part of friendly-name link. The address it the part that is sent when the user clicks the name.
    public static let friendlyLinkAddress = Self(rawValue: 4)

    /// A Uniform Resource Identifier (URI) that is automatically recognized.
    public static let autoLink = Self(rawValue: 5)

    /// An email address that is automatically recognized.
    public static let autoLinkEmail = Self(rawValue: 6)

    /// A phone number that is automatically recognized.
    public static let autoLinkPhone = Self(rawValue: 7)

    /// A file name, including the full path, that is automatically recognized.
    public static let autoLinkPath = Self(rawValue: 8)
}