// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides the content of the event that is raised for background task handlers for the hotspot authentication event.
public final class WindowsNetworkingNetworkOperators_HotspotAuthenticationEventDetails: WindowsRuntime.WinRTImport<WindowsNetworkingNetworkOperators_HotspotAuthenticationEventDetailsProjection> {
    // MARK: Windows.Networking.NetworkOperators.IHotspotAuthenticationEventDetails members

    /// Gets a GUID that uniquely identifies the authentication attempt for which this event was raised.
    /// - Returns: A GUID that uniquely identifies the connection attempt.
    public var eventToken: Swift.String {
        get throws {
            try _interop.get_EventToken()
        }
    }

    // MARK: Implementation details
}