// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// A class providing details about a Protocol Configuration Options (PCO) data change notification.
public final class WindowsNetworkingNetworkOperators_MobileBroadbandPcoDataChangeTriggerDetails: WindowsRuntime.WinRTImport<WindowsNetworkingNetworkOperators_MobileBroadbandPcoDataChangeTriggerDetailsProjection> {
    // MARK: Windows.Networking.NetworkOperators.IMobileBroadbandPcoDataChangeTriggerDetails members

    /// Gets details about a Protocol Configuration Options (PCO) data change notification.
    /// - Returns: Details about the Protocol Configuration Options (PCO) data change notification.
    public var updatedData: WindowsNetworkingNetworkOperators_MobileBroadbandPco {
        get throws {
            try COM.NullResult.unwrap(_interop.get_UpdatedData())
        }
    }

    // MARK: Implementation details
}