// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a mobile broadband device service.
public final class WindowsNetworkingNetworkOperators_MobileBroadbandDeviceService: WindowsRuntime.WinRTImport<WindowsNetworkingNetworkOperators_MobileBroadbandDeviceServiceProjection> {
    // MARK: Windows.Networking.NetworkOperators.IMobileBroadbandDeviceService members

    /// Gets the unique device service identity for the mobile broadband device service.
    /// - Returns: The unique Device Service identity for the Mobile Broadband device service.
    public var deviceServiceId: Foundation.UUID {
        get throws {
            try _interop.get_DeviceServiceId()
        }
    }

    /// Gets a list of supported device service commands for the mobile broadband device service.
    /// - Returns: A list of supported device service commands for the mobile broadband device service.
    public var supportedCommands: WindowsFoundationCollections_IVectorView<Swift.UInt32> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_SupportedCommands())
        }
    }

    /// Opens a new MobileBroadbandDeviceServiceDataSession for the mobile broadband device service.
    /// - Returns: A new data session for the Mobile Broadband device service.
    public func openDataSession() throws -> WindowsNetworkingNetworkOperators_MobileBroadbandDeviceServiceDataSession {
        try COM.NullResult.unwrap(_interop.openDataSession())
    }

    /// Opens a new MobileBroadbandDeviceServiceCommandSession for the mobile broadband device service.
    /// - Returns: A new command session for the mobile broadband device service.
    public func openCommandSession() throws -> WindowsNetworkingNetworkOperators_MobileBroadbandDeviceServiceCommandSession {
        try COM.NullResult.unwrap(_interop.openCommandSession())
    }

    // MARK: Implementation details
}