// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Describes radio states for a Mobile Broadband device.
public struct WindowsNetworkingNetworkOperators_MobileBroadbandRadioState: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The radio is off. This can be because it has been turned off using a physical switch on the device, or using a software mechanism such as **Airplane Mode** on the control panel.
    public static let off = Self()

    /// The radio is on.
    public static let on = Self(rawValue: 1)
}