// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the callback that is invoked when the effective property value of a dependency property changes.
/// - Parameter d: The DependencyObject on which the property has changed value.
/// - Parameter e: Event data that is issued by any event that tracks changes to the effective value of this property.
public typealias WindowsUIXaml_PropertyChangedCallback = (WindowsUIXaml_DependencyObject?, WindowsUIXaml_DependencyPropertyChangedEventArgs?) throws -> Swift.Void