// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the path to a property on a target element.
public final class WindowsUIXaml_TargetPropertyPath: WindowsRuntime.WinRTImport<WindowsUIXaml_TargetPropertyPathProjection> {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsUIXaml_TargetPropertyPathProjection.self))
    }

    // MARK: Windows.UI.Xaml.ITargetPropertyPathFactory members

    public convenience init(_ targetProperty: WindowsUIXaml_DependencyProperty?) throws {
        self.init(_transferringRef: try COM.NullResult.unwrap(Self._itargetPropertyPathFactory.createInstance(targetProperty)))
    }

    // MARK: Windows.UI.Xaml.ITargetPropertyPath members

    /// Gets or sets the path to the property on the target element.
    /// - Returns: The path to the property on the target element.
    public var path: WindowsUIXaml_PropertyPath {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Path())
        }
    }

    /// Gets or sets the path to the property on the target element.
    /// - Returns: The path to the property on the target element.
    public func path(_ value: WindowsUIXaml_PropertyPath?) throws {
        try _interop.put_Path(value)
    }

    /// Gets or sets the object that contains the property described by Path.
    /// - Returns: The object that contains the property described by Path.
    public var target: WindowsRuntime.IInspectable {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Target())
        }
    }

    /// Gets or sets the object that contains the property described by Path.
    /// - Returns: The object that contains the property described by Path.
    public func target(_ value: WindowsRuntime.IInspectable?) throws {
        try _interop.put_Target(value)
    }

    // MARK: Implementation details

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.TargetPropertyPath", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }

    private static var _itargetPropertyPathFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXaml_ITargetPropertyPathFactory>? = nil

    internal static var _itargetPropertyPathFactory: COM.COMInterop<CWinRT.SWRT_WindowsUIXaml_ITargetPropertyPathFactory> {
        get throws {
            try _itargetPropertyPathFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.TargetPropertyPath", id: CWinRT.SWRT_WindowsUIXaml_ITargetPropertyPathFactory.iid)
            }
        }
    }
}