// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the status of a key credential request.
public struct WindowsSecurityCredentials_KeyCredentialStatus: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The operation was successful.
    public static let success = Self()

    /// An unknown error occurred.
    public static let unknownError = Self(rawValue: 1)

    /// The credential could not be found.
    public static let notFound = Self(rawValue: 2)

    /// The request was cancelled by the user.
    public static let userCanceled = Self(rawValue: 3)

    /// The user prefers to enter a password.
    public static let userPrefersPassword = Self(rawValue: 4)

    /// The credential already exists.
    public static let credentialAlreadyExists = Self(rawValue: 5)

    /// The security device was locked.
    public static let securityDeviceLocked = Self(rawValue: 6)
}