// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the result to the application that launched the current application for results.
public final class WindowsSystem_ProtocolForResultsOperation: WindowsRuntime.WinRTImport<WindowsSystem_ProtocolForResultsOperationProjection> {
    // MARK: Windows.System.IProtocolForResultsOperation members

    /// Indicates that the application activated for results is ready to return to the application that launched it for results.
    /// - Parameter data: The data to return to the application that activated this app. 
    public func reportCompleted(_ data: WindowsFoundationCollections_ValueSet?) throws {
        try _interop.reportCompleted(data)
    }

    // MARK: Implementation details
}