// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides bank card data from the BankCardDataReceived event.
public final class WindowsDevicesPointOfService_MagneticStripeReaderBankCardDataReceivedEventArgs: WindowsRuntime.WinRTImport<WindowsDevicesPointOfService_MagneticStripeReaderBankCardDataReceivedEventArgsProjection> {
    // MARK: Windows.Devices.PointOfService.IMagneticStripeReaderBankCardDataReceivedEventArgs members

    /// Gets the account number from the swiped bank card.
    /// - Returns: The account number from the swiped bank card.
    public var accountNumber: Swift.String {
        get throws {
            try _interop.get_AccountNumber()
        }
    }

    /// Gets the expiration date from the swiped card.
    /// - Returns: The expiration date from the swiped card.
    public var expirationDate: Swift.String {
        get throws {
            try _interop.get_ExpirationDate()
        }
    }

    /// Gets the first name from the swiped bank card.
    /// - Returns: The first name from the swiped bank card.
    public var firstName: Swift.String {
        get throws {
            try _interop.get_FirstName()
        }
    }

    /// Gets the middle initial from the swiped bank card.
    /// - Returns: The middle initial from the swiped bank card.
    public var middleInitial: Swift.String {
        get throws {
            try _interop.get_MiddleInitial()
        }
    }

    /// Gets the data from the swiped bank card.
    /// - Returns: The data from the swiped bank card.
    public var report: WindowsDevicesPointOfService_MagneticStripeReaderReport {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Report())
        }
    }

    /// Gets the service code for the swiped bank card.
    /// - Returns: The service code for the swiped bank card.
    public var serviceCode: Swift.String {
        get throws {
            try _interop.get_ServiceCode()
        }
    }

    /// Gets the suffix from the swiped bank card.
    /// - Returns: The suffix from the swiped bank card.
    public var suffix: Swift.String {
        get throws {
            try _interop.get_Suffix()
        }
    }

    /// Gets the surname from the swiped bank card.
    /// - Returns: The surname from the swiped bank card.
    public var surname: Swift.String {
        get throws {
            try _interop.get_Surname()
        }
    }

    /// Gets the title from the swiped bank card.
    /// - Returns: The title from the swiped bank card.
    public var title: Swift.String {
        get throws {
            try _interop.get_Title()
        }
    }

    // MARK: Implementation details
}