// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Defines the constants that indicates the track error type.
public struct WindowsDevicesPointOfService_MagneticStripeReaderTrackErrorType: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// No specified error.
    public static let none = Self()

    /// A start sentinel error.
    public static let startSentinelError = Self(rawValue: 1)

    /// An end sentinel error.
    public static let endSentinelError = Self(rawValue: 2)

    /// A parity error.
    public static let parityError = Self(rawValue: 3)

    /// An LRC error.
    public static let lrcError = Self(rawValue: 4)

    /// An unknown error.
    public static let unknown = Self(rawValue: -1)
}