// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Describes the line styles that a receipt or slip printer station can use to print a ruled line.
public struct WindowsDevicesPointOfService_PosPrinterLineStyle: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Prints a continuous solid line.
    public static let singleSolid = Self()

    /// Prints a continuous solid line of double the normal thickness.
    public static let doubleSolid = Self(rawValue: 1)

    /// Prints a sequence of short lines separated by spaces.
    public static let broken = Self(rawValue: 2)

    /// Prints a sequence of short lines separated by a space, then followed by a very short line, followed by a space, then followed by a short line again.
    public static let chain = Self(rawValue: 3)
}