// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Determines the highest resolution the user can select for capturing video.
public struct WindowsMediaCapture_CameraCaptureUIMaxVideoResolution: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The user can select any resolution.
    public static let highestAvailable = Self()

    /// The user can select resolutions up to low definition resolutions.
    public static let lowDefinition = Self(rawValue: 1)

    /// The user can select resolutions up to standard definition resolutions.
    public static let standardDefinition = Self(rawValue: 2)

    /// The user can select resolutions up to high definition resolutions.
    public static let highDefinition = Self(rawValue: 3)
}