// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Defines values for types of media categories.
public struct WindowsMediaCapture_MediaCategory: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Media category is other.
    public static let other = Self()

    /// Media is intended for real-time communications.
    public static let communications = Self(rawValue: 1)

    /// General media.
    public static let media = Self(rawValue: 2)

    /// Media is game chat.
    public static let gameChat = Self(rawValue: 3)

    /// Media is speech.
    public static let speech = Self(rawValue: 4)
    public static let farFieldSpeech = Self(rawValue: 5)
    public static let uniformSpeech = Self(rawValue: 6)
    public static let voiceTyping = Self(rawValue: 7)
}