// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Reports the type that a markup extension can return.
public enum WindowsUIXamlMarkup_MarkupExtensionReturnTypeAttribute {
    // MARK: Implementation details
}