// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Specifies how the summary card for an appointment is displayed.
public struct WindowsApplicationModelAppointments_AppointmentSummaryCardView: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The appointment summary card is displayed by the system.
    public static let system = Self()

    /// The appointment summary card is displayed by the app that owns the appointment calendar.
    public static let app = Self(rawValue: 1)
}