// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents state specific to motion controllers.
public final class WindowsUIInputSpatial_SpatialInteractionControllerProperties: WindowsRuntime.WinRTImport<WindowsUIInputSpatial_SpatialInteractionControllerPropertiesProjection> {
    // MARK: Windows.UI.Input.Spatial.ISpatialInteractionControllerProperties members

    /// Gets whether a motion controller is experiencing a thumbstick press.
    /// - Returns: Whether the source is experiencing a thumbstick press.
    public var isThumbstickPressed: Swift.Bool {
        get throws {
            try _interop.get_IsThumbstickPressed()
        }
    }

    /// Gets whether a motion controller is experiencing a touchpad press.
    /// - Returns: Whether the source is experiencing a touchpad press.
    public var isTouchpadPressed: Swift.Bool {
        get throws {
            try _interop.get_IsTouchpadPressed()
        }
    }

    /// Gets whether a motion controller is experiencing a touchpad touch.
    /// - Returns: Whether the source is experiencing a touchpad touch.
    public var isTouchpadTouched: Swift.Bool {
        get throws {
            try _interop.get_IsTouchpadTouched()
        }
    }

    /// Gets a value between -1.0 and 1.0 representing the horizontal position of the thumbstick.
    /// - Returns: The thumbstick X value.
    public var thumbstickX: Swift.Double {
        get throws {
            try _interop.get_ThumbstickX()
        }
    }

    /// Gets a value between -1.0 and 1.0 representing the vertical position of the thumbstick.
    /// - Returns: The thumbstick Y value.
    public var thumbstickY: Swift.Double {
        get throws {
            try _interop.get_ThumbstickY()
        }
    }

    /// Gets a value between -1.0 and 1.0 representing the horizontal position of the user's finger on the touchpad.
    /// - Returns: The touchpad X value.
    public var touchpadX: Swift.Double {
        get throws {
            try _interop.get_TouchpadX()
        }
    }

    /// Gets a value between -1.0 and 1.0 representing the vertical position of the user's finger on the touchpad.
    /// - Returns: The touchpad Y value.
    public var touchpadY: Swift.Double {
        get throws {
            try _interop.get_TouchpadY()
        }
    }

    // MARK: Implementation details
}