// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides data for the SpatialInteractionSource Source events.
public final class WindowsUIInputSpatial_SpatialInteractionSourceEventArgs: WindowsRuntime.WinRTImport<WindowsUIInputSpatial_SpatialInteractionSourceEventArgsProjection> {
    // MARK: Windows.UI.Input.Spatial.ISpatialInteractionSourceEventArgs members

    /// Gets the interaction source state associated with the event.
    /// - Returns: The interaction source state.
    public var state: WindowsUIInputSpatial_SpatialInteractionSourceState {
        get throws {
            try COM.NullResult.unwrap(_interop.get_State())
        }
    }

    // MARK: Windows.UI.Input.Spatial.ISpatialInteractionSourceEventArgs2 members

    /// Gets the kind of press or release associated with the event.
    /// - Returns: The press kind.
    public var pressKind: WindowsUIInputSpatial_SpatialInteractionPressKind {
        get throws {
            try _ispatialInteractionSourceEventArgs2.get_PressKind()
        }
    }

    // MARK: Implementation details

    private var _ispatialInteractionSourceEventArgs2_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIInputSpatial_ISpatialInteractionSourceEventArgs2>? = nil

    internal var _ispatialInteractionSourceEventArgs2: COM.COMInterop<CWinRT.SWRT_WindowsUIInputSpatial_ISpatialInteractionSourceEventArgs2> {
        get throws {
            try _ispatialInteractionSourceEventArgs2_storage.lazyInit {
                try _queryInterfacePointer(CWinRT.SWRT_WindowsUIInputSpatial_ISpatialInteractionSourceEventArgs2.iid).cast(to: CWinRT.SWRT_WindowsUIInputSpatial_ISpatialInteractionSourceEventArgs2.self)
            }
        }
    }

    deinit {
        _ispatialInteractionSourceEventArgs2_storage?.release()
    }
}