// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the current state of the gamepad.
public struct WindowsGamingInput_GamepadReading: Hashable, Codable {
    /// Time when the state was retrieved from the gamepad.
    public var timestamp: Swift.UInt64

    /// The state of the gamepad's buttons. This will be a combination of values in the GamepadButtons enumeration.
    public var buttons: WindowsGamingInput_GamepadButtons

    /// The position of the left trigger. The value is between 0.0 (not depressed) and 1.0 (fully depressed).
    public var leftTrigger: Swift.Double

    /// The position of the right trigger. The value is between 0.0 (not depressed) and 1.0 (fully depressed).
    public var rightTrigger: Swift.Double

    /// The position of the left thumbstick on the X-axis. The value is between -1.0 and 1.0.
    public var leftThumbstickX: Swift.Double

    /// The position of the left thumbstick on the Y-axis. The value is between -1.0 and 1.0.
    public var leftThumbstickY: Swift.Double

    /// The position of the right thumbstick on the X-axis. The value is between -1.0 and 1.0.
    public var rightThumbstickX: Swift.Double

    /// The position of the right thumbstick on the Y-axis. The value is between -1.0 and 1.0.
    public var rightThumbstickY: Swift.Double

    public init() {
        self.timestamp = 0
        self.buttons = .init()
        self.leftTrigger = 0
        self.rightTrigger = 0
        self.leftThumbstickX = 0
        self.leftThumbstickY = 0
        self.rightThumbstickX = 0
        self.rightThumbstickY = 0
    }

    public init(timestamp: Swift.UInt64, buttons: WindowsGamingInput_GamepadButtons, leftTrigger: Swift.Double, rightTrigger: Swift.Double, leftThumbstickX: Swift.Double, leftThumbstickY: Swift.Double, rightThumbstickX: Swift.Double, rightThumbstickY: Swift.Double) {
        self.timestamp = timestamp
        self.buttons = buttons
        self.leftTrigger = leftTrigger
        self.rightTrigger = rightTrigger
        self.leftThumbstickX = leftThumbstickX
        self.leftThumbstickY = leftThumbstickY
        self.rightThumbstickX = rightThumbstickX
        self.rightThumbstickY = rightThumbstickY
    }
}