// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides access to the IsAvailable property.
public protocol WindowsStorage_IStorageFilePropertiesWithAvailabilityProtocol: IInspectableProtocol {
    /// Indicates if the file is local, is cached locally, or can be downloaded.
    /// - Returns: **True** if the file is local, is cached locally, or can be downloaded. Otherwise, **false**.
    var isAvailable: Swift.Bool { get throws }
}

/// Provides access to the IsAvailable property.
public typealias WindowsStorage_IStorageFilePropertiesWithAvailability = any WindowsStorage_IStorageFilePropertiesWithAvailabilityProtocol