// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the object that is passed as a parameter to the event handler that is invoked when the state of a signal line changes on the serial port.
public final class WindowsDevicesSerialCommunication_PinChangedEventArgs: WindowsRuntime.WinRTImport<WindowsDevicesSerialCommunication_PinChangedEventArgsProjection> {
    // MARK: Windows.Devices.SerialCommunication.IPinChangedEventArgs members

    /// Gets the type of signal change that caused the event on the serial port.
    /// - Returns: One of the values defined in SerialPinChange enumeration.
    public var pinChange: WindowsDevicesSerialCommunication_SerialPinChange {
        get throws {
            try _interop.get_PinChange()
        }
    }

    // MARK: Implementation details
}