// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents the arguments which the HID API sends as part of an input-report event.
public final class WindowsDevicesHumanInterfaceDevice_HidInputReportReceivedEventArgs: WindowsRuntime.WinRTImport<WindowsDevicesHumanInterfaceDevice_HidInputReportReceivedEventArgsProjection> {
    // MARK: Windows.Devices.HumanInterfaceDevice.IHidInputReportReceivedEventArgs members

    /// Gets the input report.
    /// - Returns: A **HidInputReport** object.
    public var report: WindowsDevicesHumanInterfaceDevice_HidInputReport {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Report())
        }
    }

    // MARK: Implementation details
}