// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Defines the server types for syncing.
public struct WindowsApplicationModelUserDataAccountsSystemAccess_DeviceAccountServerType: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Exchange server
    public static let exchange = Self()

    /// POP server
    public static let pop = Self(rawValue: 1)

    /// IMAP server
    public static let imap = Self(rawValue: 2)
}