// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Indicates the capabilities of a particular casting device.
public struct WindowsMediaCasting_CastingPlaybackTypes: OptionSet, Hashable, Codable {
    public var rawValue: Swift.UInt32

    public init(rawValue: Swift.UInt32 = 0) {
        self.rawValue = rawValue
    }

    /// The casting device does not support playback.
    public static let none = Self()

    /// The casting device supports audio playback.
    public static let audio = Self(rawValue: 1)

    /// The casting device supports video playback.
    public static let video = Self(rawValue: 2)

    /// The casting device supports image playback.
    public static let picture = Self(rawValue: 4)
}