// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides access to information about an item (cell) in a spreadsheet.
public protocol WindowsUIXamlAutomationProvider_ISpreadsheetItemProviderProtocol: IInspectableProtocol {
    /// Gets the formula for this spreadsheet cell, as a string.
    /// - Returns: The formula for this cell, as a string.
    var formula: Swift.String { get throws }

    /// Returns an array of objects that represent the annotations associated with this spreadsheet cell.
    /// - Returns: An array of IRawElementProviderSimple interfaces for Microsoft UI Automation elements that represent the annotations associated with the spreadsheet cell.
    func getAnnotationObjects() throws -> [WindowsUIXamlAutomationProvider_IRawElementProviderSimple?]

    /// Returns an array of annotation type identifiers indicating the types of annotations that are associated with this spreadsheet cell.
    /// - Returns: An array of annotation type identifiers, which contains one entry for each type of annotation associated with the spreadsheet cell. For a list of possible values, see AnnotationType.
    func getAnnotationTypes() throws -> [WindowsUIXamlAutomation_AnnotationType]
}

/// Provides access to information about an item (cell) in a spreadsheet.
public typealias WindowsUIXamlAutomationProvider_ISpreadsheetItemProvider = any WindowsUIXamlAutomationProvider_ISpreadsheetItemProviderProtocol