// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Provides access to items (cells) in a spreadsheet.
public protocol WindowsUIXamlAutomationProvider_ISpreadsheetProviderProtocol: IInspectableProtocol {
    /// Returns a Microsoft UI Automation element that represents the spreadsheet cell that has the specified name.
    /// - Parameter name: The name of the target cell.
    /// - Returns: A Microsoft UI Automation element that represents the target cell.
    func getItemByName(_ name: Swift.String) throws -> WindowsUIXamlAutomationProvider_IRawElementProviderSimple
}

/// Provides access to items (cells) in a spreadsheet.
public typealias WindowsUIXamlAutomationProvider_ISpreadsheetProvider = any WindowsUIXamlAutomationProvider_ISpreadsheetProviderProtocol