// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Stores a DeferralCompletedHandler to be invoked upon completion of the deferral and manipulates the state of the deferral.
public final class WindowsFoundation_Deferral: WindowsRuntime.WinRTImport<WindowsFoundation_DeferralProjection>, WindowsFoundation_IClosableProtocol {
    // MARK: Windows.Foundation.IDeferralFactory members

    public convenience init(_ handler: WindowsFoundation_DeferralCompletedHandler?) throws {
        self.init(_transferringRef: try COM.NullResult.unwrap(Self._ideferralFactory.create(handler)))
    }

    // MARK: Windows.Foundation.IDeferral members

    /// If the DeferralCompletedHandler has not yet been invoked, this will call it and drop the reference to the delegate.
    public func complete() throws {
        try _interop.complete()
    }

    // MARK: Windows.Foundation.IClosable members

    /// If the DeferralCompletedHandler has not yet been invoked, this will call it and drop the reference to the delegate.
    public func close() throws {
        try _iclosable.close()
    }

    // MARK: Implementation details

    private var _iclosable_storage: COM.COMInterop<CWinRT.SWRT_WindowsFoundation_IClosable>? = nil

    internal var _iclosable: COM.COMInterop<CWinRT.SWRT_WindowsFoundation_IClosable> {
        get throws {
            try _iclosable_storage.lazyInit {
                try _queryInterfacePointer(CWinRT.SWRT_WindowsFoundation_IClosable.iid).cast(to: CWinRT.SWRT_WindowsFoundation_IClosable.self)
            }
        }
    }

    deinit {
        _iclosable_storage?.release()
    }

    private static var _ideferralFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsFoundation_IDeferralFactory>? = nil

    internal static var _ideferralFactory: COM.COMInterop<CWinRT.SWRT_WindowsFoundation_IDeferralFactory> {
        get throws {
            try _ideferralFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.Foundation.Deferral", id: CWinRT.SWRT_WindowsFoundation_IDeferralFactory.iid)
            }
        }
    }
}