// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a reference to an IMemoryBuffer object.
public protocol WindowsFoundation_IMemoryBufferReferenceProtocol: WindowsFoundation_IClosableProtocol {
    /// Gets the size of the memory buffer in bytes.
    /// - Returns: The size of the memory buffer in bytes.
    var capacity: Swift.UInt32 { get throws }

    /// Occurs when MemoryBuffer.Close has been called, but before this IMemoryBufferReference has been closed.
    func closed(adding handler: WindowsFoundation_TypedEventHandler<WindowsFoundation_IMemoryBufferReference?, WindowsRuntime.IInspectable?>?) throws -> WindowsRuntime.EventRegistration
    func closed(removing cookie: WindowsRuntime.EventRegistrationToken) throws
}

/// Represents a reference to an IMemoryBuffer object.
public typealias WindowsFoundation_IMemoryBufferReference = any WindowsFoundation_IMemoryBufferReferenceProtocol