// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a single UI automation annotation.
public final class WindowsUIXamlAutomationPeers_AutomationPeerAnnotation: WindowsRuntime.WinRTImport<WindowsUIXamlAutomationPeers_AutomationPeerAnnotationProjection> {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_transferringRef: try Self._iactivationFactory.activateInstance(projection: WindowsUIXamlAutomationPeers_AutomationPeerAnnotationProjection.self))
    }

    // MARK: Windows.UI.Xaml.Automation.Peers.IAutomationPeerAnnotationFactory members

    public convenience init(_ type: WindowsUIXamlAutomation_AnnotationType) throws {
        self.init(_transferringRef: try COM.NullResult.unwrap(Self._iautomationPeerAnnotationFactory.createInstance(type)))
    }

    public convenience init(_ type: WindowsUIXamlAutomation_AnnotationType, _ peer: WindowsUIXamlAutomationPeers_AutomationPeer?) throws {
        self.init(_transferringRef: try COM.NullResult.unwrap(Self._iautomationPeerAnnotationFactory.createWithPeerParameter(type, peer)))
    }

    // MARK: Windows.UI.Xaml.Automation.Peers.IAutomationPeerAnnotation members

    /// Gets or sets the automation peer of the element that implements the annotation.
    /// - Returns: The automation peer of the element that implements the annotation.
    public var peer: WindowsUIXamlAutomationPeers_AutomationPeer {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Peer())
        }
    }

    /// Gets or sets the automation peer of the element that implements the annotation.
    /// - Returns: The automation peer of the element that implements the annotation.
    public func peer(_ value: WindowsUIXamlAutomationPeers_AutomationPeer?) throws {
        try _interop.put_Peer(value)
    }

    /// Gets or sets the type of the annotation.
    /// - Returns: The type of the annotation.
    public var type: WindowsUIXamlAutomation_AnnotationType {
        get throws {
            try _interop.get_Type()
        }
    }

    /// Gets or sets the type of the annotation.
    /// - Returns: The type of the annotation.
    public func type(_ value: WindowsUIXamlAutomation_AnnotationType) throws {
        try _interop.put_Type(value)
    }

    // MARK: Windows.UI.Xaml.Automation.Peers.IAutomationPeerAnnotationStatics members

    /// Identifies the AutomationPeerAnnotation.Peer property.
    /// - Returns: The AutomationPeerAnnotation.Peer property.
    public static var peerProperty: WindowsUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_iautomationPeerAnnotationStatics.get_PeerProperty())
        }
    }

    /// Identifies the AutomationPeerAnnotation.Type property.
    /// - Returns: The AutomationPeerAnnotation.Type property.
    public static var typeProperty: WindowsUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_iautomationPeerAnnotationStatics.get_TypeProperty())
        }
    }

    // MARK: Implementation details

    private static var _iactivationFactory_storage: COM.COMInterop<CWinRT.SWRT_IActivationFactory>? = nil

    internal static var _iactivationFactory: COM.COMInterop<CWinRT.SWRT_IActivationFactory> {
        get throws {
            try _iactivationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Automation.Peers.AutomationPeerAnnotation", id: CWinRT.SWRT_IActivationFactory.iid)
            }
        }
    }

    private static var _iautomationPeerAnnotationFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IAutomationPeerAnnotationFactory>? = nil

    internal static var _iautomationPeerAnnotationFactory: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IAutomationPeerAnnotationFactory> {
        get throws {
            try _iautomationPeerAnnotationFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Automation.Peers.AutomationPeerAnnotation", id: CWinRT.SWRT_WindowsUIXamlAutomationPeers_IAutomationPeerAnnotationFactory.iid)
            }
        }
    }

    private static var _iautomationPeerAnnotationStatics_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IAutomationPeerAnnotationStatics>? = nil

    internal static var _iautomationPeerAnnotationStatics: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IAutomationPeerAnnotationStatics> {
        get throws {
            try _iautomationPeerAnnotationStatics_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Automation.Peers.AutomationPeerAnnotation", id: CWinRT.SWRT_WindowsUIXamlAutomationPeers_IAutomationPeerAnnotationStatics.iid)
            }
        }
    }
}