// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Exposes a ListViewItem to Microsoft UI Automation.
open class WindowsUIXamlAutomationPeers_ListViewItemAutomationPeer: WindowsRuntime.WinRTComposableClass {
    // MARK: Windows.UI.Xaml.Automation.Peers.IListViewItemAutomationPeerFactory members

    public convenience init(_ owner: WindowsUIXamlControls_ListViewItem?) throws {
        try self.init(_compose: Self.self != WindowsUIXamlAutomationPeers_ListViewItemAutomationPeer.self) {
            (baseInterface, innerInterface: inout IInspectablePointer?) in
            try COM.NullResult.unwrap(Self._ilistViewItemAutomationPeerFactory.createInstanceWithOwner(owner, baseInterface, &innerInterface))
        }
    }

    // MARK: Implementation details

    private var _ilistViewItemAutomationPeer_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListViewItemAutomationPeer>? = nil

    internal var _ilistViewItemAutomationPeer: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListViewItemAutomationPeer> {
        get throws {
            try _ilistViewItemAutomationPeer_storage.lazyInit {
                try _queryInnerInterfacePointer(CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListViewItemAutomationPeer.iid).cast(to: CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListViewItemAutomationPeer.self)
            }
        }
    }

    public init(_transferringRef comPointer: Swift.UnsafeMutablePointer<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListViewItemAutomationPeer>) {
        super.init(_transferringRef: IInspectablePointer.cast(comPointer))
    }

    public override init<Interface>(_compose: Swift.Bool, _factory: ComposableFactory<Interface>) throws {
        try super.init(_compose: _compose, _factory: _factory)
    }

    deinit {
        _ilistViewItemAutomationPeer_storage?.release()
    }

    private static var _ilistViewItemAutomationPeerFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListViewItemAutomationPeerFactory>? = nil

    internal static var _ilistViewItemAutomationPeerFactory: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListViewItemAutomationPeerFactory> {
        get throws {
            try _ilistViewItemAutomationPeerFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Automation.Peers.ListViewItemAutomationPeer", id: CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListViewItemAutomationPeerFactory.iid)
            }
        }
    }
}