// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Exposes ListBox types to Microsoft UI Automation.
open class WindowsUIXamlAutomationPeers_ListBoxAutomationPeer: WindowsRuntime.WinRTComposableClass {
    // MARK: Windows.UI.Xaml.Automation.Peers.IListBoxAutomationPeerFactory members

    public convenience init(_ owner: WindowsUIXamlControls_ListBox?) throws {
        try self.init(_compose: Self.self != WindowsUIXamlAutomationPeers_ListBoxAutomationPeer.self) {
            (baseInterface, innerInterface: inout IInspectablePointer?) in
            try COM.NullResult.unwrap(Self._ilistBoxAutomationPeerFactory.createInstanceWithOwner(owner, baseInterface, &innerInterface))
        }
    }

    // MARK: Implementation details

    private var _ilistBoxAutomationPeer_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListBoxAutomationPeer>? = nil

    internal var _ilistBoxAutomationPeer: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListBoxAutomationPeer> {
        get throws {
            try _ilistBoxAutomationPeer_storage.lazyInit {
                try _queryInnerInterfacePointer(CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListBoxAutomationPeer.iid).cast(to: CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListBoxAutomationPeer.self)
            }
        }
    }

    public init(_transferringRef comPointer: Swift.UnsafeMutablePointer<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListBoxAutomationPeer>) {
        super.init(_transferringRef: IInspectablePointer.cast(comPointer))
    }

    public override init<Interface>(_compose: Swift.Bool, _factory: ComposableFactory<Interface>) throws {
        try super.init(_compose: _compose, _factory: _factory)
    }

    deinit {
        _ilistBoxAutomationPeer_storage?.release()
    }

    private static var _ilistBoxAutomationPeerFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListBoxAutomationPeerFactory>? = nil

    internal static var _ilistBoxAutomationPeerFactory: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListBoxAutomationPeerFactory> {
        get throws {
            try _ilistBoxAutomationPeerFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Automation.Peers.ListBoxAutomationPeer", id: CWinRT.SWRT_WindowsUIXamlAutomationPeers_IListBoxAutomationPeerFactory.iid)
            }
        }
    }
}