// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Exposes Pivot types to Microsoft UI Automation.
public final class WindowsUIXamlAutomationPeers_PivotAutomationPeer: WindowsRuntime.WinRTImport<WindowsUIXamlAutomationPeers_PivotAutomationPeerProjection>, WindowsUIXamlAutomationProvider_ISelectionProviderProtocol, WindowsUIXamlAutomationProvider_IScrollProviderProtocol {
    // MARK: Windows.UI.Xaml.Automation.Peers.IPivotAutomationPeerFactory members

    public convenience init(_ owner: WindowsUIXamlControls_Pivot?) throws {
        self.init(_transferringRef: try COM.NullResult.unwrap(Self._ipivotAutomationPeerFactory.createInstanceWithOwner(owner)))
    }

    // MARK: Windows.UI.Xaml.Automation.Provider.ISelectionProvider members

    /// Gets a value that indicates whether the control allows more than one child element to be selected concurrently.
    /// - Returns: **true** if multiple selection is allowed; otherwise, **false**.
    public var canSelectMultiple: Swift.Bool {
        get throws {
            try _iselectionProvider.get_CanSelectMultiple()
        }
    }

    /// Gets a value that indicates whether the control requires at least one child element to be selected.
    /// - Returns: **true** if selection is required; otherwise, **false**.
    public var isSelectionRequired: Swift.Bool {
        get throws {
            try _iselectionProvider.get_IsSelectionRequired()
        }
    }

    /// Retrieves a Microsoft UI Automation provider for each child element that is selected.
    /// - Returns: A generic list of Microsoft UI Automation providers.
    public func getSelection() throws -> [WindowsUIXamlAutomationProvider_IRawElementProviderSimple?] {
        try _iselectionProvider.getSelection()
    }

    // MARK: Windows.UI.Xaml.Automation.Provider.IScrollProvider members

    /// Gets the current horizontal scroll position.
    /// - Returns: The horizontal scroll position as a percentage of the total content area within the control.
    public var horizontalScrollPercent: Swift.Double {
        get throws {
            try _iscrollProvider.get_HorizontalScrollPercent()
        }
    }

    /// Gets the current horizontal view size.
    /// - Returns: The horizontal size of the viewable region as a percentage of the total content area within the control.
    public var horizontalViewSize: Swift.Double {
        get throws {
            try _iscrollProvider.get_HorizontalViewSize()
        }
    }

    /// Gets a value that indicates whether the control can scroll horizontally.
    /// - Returns: **true** if the control can scroll horizontally; otherwise, **false**.
    public var horizontallyScrollable: Swift.Bool {
        get throws {
            try _iscrollProvider.get_HorizontallyScrollable()
        }
    }

    /// Gets the current vertical scroll position.
    /// - Returns: The vertical scroll position as a percentage of the total content area within the control.
    public var verticalScrollPercent: Swift.Double {
        get throws {
            try _iscrollProvider.get_VerticalScrollPercent()
        }
    }

    /// Gets the current vertical view size.
    /// - Returns: The vertical size of the viewable region as a percentage of the total content area within the control.
    public var verticalViewSize: Swift.Double {
        get throws {
            try _iscrollProvider.get_VerticalViewSize()
        }
    }

    /// Gets a value that indicates whether the control can scroll vertically.
    /// - Returns: **true** if the control can scroll vertically; otherwise, **false**.
    public var verticallyScrollable: Swift.Bool {
        get throws {
            try _iscrollProvider.get_VerticallyScrollable()
        }
    }

    /// Scrolls the visible region of the content area horizontally, vertically, or both.
    /// - Parameter horizontalAmount: The horizontal increment that is specific to the control. Pass NoScroll if the control cannot be scrolled in this direction.
    /// - Parameter verticalAmount: The vertical increment that is specific to the control. Pass NoScroll if the control cannot be scrolled in this direction.
    public func scroll(_ horizontalAmount: WindowsUIXamlAutomation_ScrollAmount, _ verticalAmount: WindowsUIXamlAutomation_ScrollAmount) throws {
        try _iscrollProvider.scroll(horizontalAmount, verticalAmount)
    }

    /// Sets the horizontal and vertical scroll position as a percentage of the total content area within the control.
    /// - Parameter horizontalPercent: The horizontal position as a percentage of the content area's total range. Pass NoScroll if the control cannot be scrolled in this direction.
    /// - Parameter verticalPercent: The vertical position as a percentage of the content area's total range. Pass NoScroll if the control cannot be scrolled in this direction.
    public func setScrollPercent(_ horizontalPercent: Swift.Double, _ verticalPercent: Swift.Double) throws {
        try _iscrollProvider.setScrollPercent(horizontalPercent, verticalPercent)
    }

    // MARK: Implementation details

    private var _iselectionProvider_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationProvider_ISelectionProvider>? = nil

    internal var _iselectionProvider: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationProvider_ISelectionProvider> {
        get throws {
            try _iselectionProvider_storage.lazyInit {
                try _queryInterfacePointer(CWinRT.SWRT_WindowsUIXamlAutomationProvider_ISelectionProvider.iid).cast(to: CWinRT.SWRT_WindowsUIXamlAutomationProvider_ISelectionProvider.self)
            }
        }
    }

    private var _iscrollProvider_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationProvider_IScrollProvider>? = nil

    internal var _iscrollProvider: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationProvider_IScrollProvider> {
        get throws {
            try _iscrollProvider_storage.lazyInit {
                try _queryInterfacePointer(CWinRT.SWRT_WindowsUIXamlAutomationProvider_IScrollProvider.iid).cast(to: CWinRT.SWRT_WindowsUIXamlAutomationProvider_IScrollProvider.self)
            }
        }
    }

    deinit {
        _iselectionProvider_storage?.release()
        _iscrollProvider_storage?.release()
    }

    private static var _ipivotAutomationPeerFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IPivotAutomationPeerFactory>? = nil

    internal static var _ipivotAutomationPeerFactory: COM.COMInterop<CWinRT.SWRT_WindowsUIXamlAutomationPeers_IPivotAutomationPeerFactory> {
        get throws {
            try _ipivotAutomationPeerFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.UI.Xaml.Automation.Peers.PivotAutomationPeer", id: CWinRT.SWRT_WindowsUIXamlAutomationPeers_IPivotAutomationPeerFactory.iid)
            }
        }
    }
}