// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Represents a gyrometer reading.
public final class WindowsDevicesSensors_GyrometerReading: WindowsRuntime.WinRTImport<WindowsDevicesSensors_GyrometerReadingProjection> {
    // MARK: Windows.Devices.Sensors.IGyrometerReading members

    /// Gets the angular velocity, in degrees per second, about the x-axis.
    /// - Returns: The angular velocity, in degrees per second, about the x-axis.
    public var angularVelocityX: Swift.Double {
        get throws {
            try _interop.get_AngularVelocityX()
        }
    }

    /// Gets the angular velocity, in degrees per second, about the y-axis.
    /// - Returns: The angular velocity, in degrees per second, about the y-axis.
    public var angularVelocityY: Swift.Double {
        get throws {
            try _interop.get_AngularVelocityY()
        }
    }

    /// Gets the angular velocity, in degrees per second, about the z-axis.
    /// - Returns: The angular velocity, in degrees per second, about the z-axis.
    public var angularVelocityZ: Swift.Double {
        get throws {
            try _interop.get_AngularVelocityZ()
        }
    }

    /// Gets the time at which the sensor reported the reading.
    /// - Returns: The time at which the sensor reported the reading.
    public var timestamp: WindowsFoundation_DateTime {
        get throws {
            try _interop.get_Timestamp()
        }
    }

    // MARK: Windows.Devices.Sensors.IGyrometerReading2 members

    /// Gets the performance count associated with the reading. This allows the reading to be synchronized with other devices and processes on the system.
    /// - Returns: The performance count for the reading. Null if this property is not supported on the sensor.
    public var performanceCount: WindowsFoundation_IReference<WindowsFoundation_TimeSpan>? {
        get throws {
            try _igyrometerReading2.get_PerformanceCount()
        }
    }

    /// Gets the data properties reported by the sensor.
    /// - Returns: Contains a key/value pair for each data property reported by the sensor for the given reading. The key is a string of the property key, and the value is the value of the property that the key represents.
    public var properties: WindowsFoundationCollections_IMapView<Swift.String, WindowsRuntime.IInspectable?> {
        get throws {
            try COM.NullResult.unwrap(_igyrometerReading2.get_Properties())
        }
    }

    // MARK: Implementation details

    private var _igyrometerReading2_storage: COM.COMInterop<CWinRT.SWRT_WindowsDevicesSensors_IGyrometerReading2>? = nil

    internal var _igyrometerReading2: COM.COMInterop<CWinRT.SWRT_WindowsDevicesSensors_IGyrometerReading2> {
        get throws {
            try _igyrometerReading2_storage.lazyInit {
                try _queryInterfacePointer(CWinRT.SWRT_WindowsDevicesSensors_IGyrometerReading2.iid).cast(to: CWinRT.SWRT_WindowsDevicesSensors_IGyrometerReading2.self)
            }
        }
    }

    deinit {
        _igyrometerReading2_storage?.release()
    }
}