// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// The type of step taken according to the pedometer.
public struct WindowsDevicesSensors_PedometerStepKind: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// An unknown step type.
    public static let unknown = Self()

    /// A walking step.
    public static let walking = Self(rawValue: 1)

    /// A running step.
    public static let running = Self(rawValue: 2)
}