// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// A threshold for the ProximitySensor. When the threshold conditions are met, the sensor trigger will activate.
public final class WindowsDevicesSensors_ProximitySensorDataThreshold: WindowsRuntime.WinRTImport<WindowsDevicesSensors_ProximitySensorDataThresholdProjection>, WindowsDevicesSensors_ISensorDataThresholdProtocol {
    // MARK: Windows.Devices.Sensors.IProximitySensorDataThresholdFactory members

    public convenience init(_ sensor: WindowsDevicesSensors_ProximitySensor?) throws {
        self.init(_transferringRef: try COM.NullResult.unwrap(Self._iproximitySensorDataThresholdFactory.create(sensor)))
    }

    // MARK: Implementation details

    private static var _iproximitySensorDataThresholdFactory_storage: COM.COMInterop<CWinRT.SWRT_WindowsDevicesSensors_IProximitySensorDataThresholdFactory>? = nil

    internal static var _iproximitySensorDataThresholdFactory: COM.COMInterop<CWinRT.SWRT_WindowsDevicesSensors_IProximitySensorDataThresholdFactory> {
        get throws {
            try _iproximitySensorDataThresholdFactory_storage.lazyInit {
                try WindowsRuntime.getActivationFactoryPointer(activatableId: "Windows.Devices.Sensors.ProximitySensorDataThreshold", id: CWinRT.SWRT_WindowsDevicesSensors_IProximitySensorDataThresholdFactory.iid)
            }
        }
    }
}