// Generated by swift-winrt
// swiftlint:disable all

import CWinRT
import WindowsRuntime
import UWP
import struct Foundation.UUID

/// Indicates whether power or precision should be optimized for sensors.
public struct WindowsDevicesSensors_SensorOptimizationGoal: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// This sensor will prioritize precision over power efficiency.
    public static let precision = Self()

    /// This sensor will prioritize power efficiency over precision depending on the hardware available.
    public static let powerEfficiency = Self(rawValue: 1)
}